
// File generated by darts version 11.1.51, Thu Aug 20 07:51:37 2015
// Copyright(c) 1996-2011 Target Compiler Technologies NV
// All rights reserved.
// C:\Program Files\Target Compiler Technologies\DSP4.5.3.1-11R1.16\bin\WINbin\darts.exe -B +F -IC:/Program Files/Target Compiler Technologies/DSP4.5.3.1-11R1.16/designs/coyote41/lib +p -d -IC:/TFS/Accesories/Main/Farlander3/Common/DSP/coyote_hw/rom_c413/inc -IC:/TFS/Accesories/Main/Farlander3/Common/DSP/ccos/osincludes -IC:/TFS/Accesories/Main/Farlander3/Common/DSP/ccos -IC:/PROGRA~1/TARGET~1/designs/coyote41/lib/runtime/include -IC:/Program Files/Target Compiler Technologies/DSP4.5.3.1-11R1.16/designs/coyote41/lib/runtime/include -DFEATURE_APP -DCFG_DSP_VERSION=453 -DCFG_ROM_VERSION=453 -DCFG_OS_VERSION=0x0117 -DCFG_COMPILER_VERSION=41 -DCFG_COMPILER_RELEASE=9 -D__chess__ -D__tct_patch__=16 -O -p -r -icoyote41_darts.as -nb +u C:/ccos_farlander3/app/rom453/dsp453/DSP4.5.3.1-11R1.16/release/dummycod.elf coyote41

// Release: coyote41 11R1.16

.text_segment PMEM   7021	   
.entry_point
.label appMain
	/*   7021       */    	i0 = (7026)
	/*   7022       */    	nm0 = (1)
	/*   7023       */    	ymem[104] = i0
	/*   7024       */    	xmem[3584] = nm0
.label appMain__end
	/*   7025       */    	ret
.label appRun
	/*   7026       */    	i0 = (7026)
	/*   7027       */    	ymem[104] = i0
.label appRun__end
	/*   7028       */    	ret

.bss_segment XMEM     64	    1

.data_segment XMEM   3584	   
.label x_AppBlobCount
	0xa

.data_segment YMEM   7168	   
.label X_BY_CustomHandler
	0x0
	0x0
	0x0
	0x0
	0x0
	0x0
	0x0
	0x0
	0x0
	0x0
	0x0
	0x0
	0x0
	0x0
	0x0
	0x0

.stack XMEM 65 65

.stack XMEM 65 65
