
// File generated by darts version 11.1.51, Thu Aug 20 07:51:23 2015
// Copyright(c) 1996-2011 Target Compiler Technologies NV
// All rights reserved.
// C:\Program Files\Target Compiler Technologies\DSP4.5.3.1-11R1.16\bin\WINbin\darts.exe -B +F -IC:/Program Files/Target Compiler Technologies/DSP4.5.3.1-11R1.16/designs/coyote41/lib +p -d -IC:/TFS/Accesories/Main/Farlander3/Common/DSP/ccos/initincludes -IC:/TFS/Accesories/Main/Farlander3/Common/DSP/ccos/osincludes -IC:/TFS/Accesories/Main/Farlander3/Common/DSP/ccos -IC:/Program Files/Target Compiler Technologies/DSP4.5.3.1-11R1.16/designs/coyote41/lib/runtime/include -DFEATURE_INIT -DCFG_DSP_VERSION=453 -DCFG_ROM_VERSION=453 -DCFG_OS_VERSION=0x0117 -DCFG_COMPILER_VERSION=41 -DCFG_COMPILER_RELEASE=9 -D__chess__ -D__tct_patch__=16 -O -p -r -icoyote41_darts.as -nb +u C:/ccos_farlander3/init/rom453/dsp453/DSP4.5.3.1-11R1.16/release/testinit453.elf coyote41

// Release: coyote41 11R1.16

.text_segment PMEM     45	   
.label block_int
	/*     45       */    	callint 1251

.text_segment PMEM     48	   
.label IntVectorWico
	/*     48       */    	nop
	/*     49       */    	nop
	/*     50       */    	nop
	/*     51       */    	nop
	/*     52       */    	callint 140
.label IIC_InterruptTable
	/*     53       */    	callint 1272
	/*     54       */    	callint 1272

.text_segment PMEM     64	   
.entry_point
.label initMain
	/*     64       */    	i11 = (8192)
	/*     65       */    	nm11 = (0)
.label initMain__end
	/*     66       */    	jmp 478
.label loadData
	/*     67       */    	x3 = (69)
	/*     68       */    	jmp 32776
.label label
	/*     69       */    	nop
	/*     70       */    	ret
.label ReadPmem
	/*     71       */    	a0g = (0)
	/*     72       */    	a0h, xtnd  = code[i0]
	/*     73       */    	a0l = inp(16)
	/*     74       */    	xmem[252] = a0l
	/*     75       */    	ret
.label setInterruptmask
	/*     76       */    	outp(28) = x1
	/*     77       */    	outp(29) = x1
	/*     78       */    	outp(30) = x1
	/*     79       */    	outp(26) = x0
	/*     80       */    	outp(27) = x0
	/*     81       */    	outp(31) = x0
.label setInterruptmask__end
	/*     82       */    	ret
.label handleFatalError
	/*     83       */    	anop; x2 = x0
	/*     84       */    	x0 = (0)
	/*     85       */    	x1 = (1)
	/*     86       */    	call 76
	/*     87       */    	xmem[64] = x2
.label xy__inlined__1__InitCode__handleFatalError_
	/*     88       */    	halt
	/*     89       */    	nop
	/*     90       */    	jmp 88
.label handleFatalError__end
	/*     91       */    	ret
.label rf2401ReadRegister
	/*     92       */    	i0 = (1)
	/*     93       */    	outp(237) = i0
	/*     94       */    	i11 = i11 - 1
	/*     95       */    	outp(253) = x1
	/*     96       */    	b0 = (0)
.label TGT_Frf2401ReadRegister_5
	/*     97       */    	a0 = inp(247)
	/*     98       */    	b1 = (8)
	/*     99       */    	a0&b1
	/*    100       */    	xmem[i11 + 0] = b0
	/*    101       */    	if (a==0) jmp 105
	/*    102       */    	i11 = i11 + 1
	/*    103       */    	x0 = inp(235)
	/*    104       */    	ret
.label TGT_Frf2401ReadRegister_13
	/*    105       */    	x0 = (1)
	/*    106       */    	call 451
	/*    107       */    	b0 = xmem[i11 + 0]
	/*    108       */    	b0+=1
	/*    109       */    	a0 = (1000)
	/*    110       */    	b0-a0
	/*    111       */    	if (b<0) jmp 97
	/*    112       */    	i11 = i11 + 1
	/*    113       */    	x0 = (65535)
.label rf2401ReadRegister__end
	/*    114       */    	ret
.label rf2401WriteReg
	/*    115       */    	outp(238) = nm11
	/*    116       */    	a0 = +x1; b0 = nm11
	/*    117       */    	b1 = (288)
	/*    118       */    	b1= b1|a0
	/*    119       */    	outp(235) = x2
	/*    120       */    	i11 = i11 - 1
	/*    121       */    	outp(253) = b1
.label TGT_Frf2401WriteReg_7
	/*    122       */    	a0 = inp(247)
	/*    123       */    	b1 = (8)
	/*    124       */    	a0&b1
	/*    125       */    	xmem[i11 + 0] = b0
	/*    126       */    	if (a==0) jmp 130
	/*    127       */    	i11 = i11 + 1
	/*    128       */    	x0 = (0)
	/*    129       */    	ret
.label TGT_Frf2401WriteReg_15
	/*    130       */    	x0 = (1)
	/*    131       */    	call 451
	/*    132       */    	b0 = xmem[i11 + 0]
	/*    133       */    	b0+=1
	/*    134       */    	a0 = (1000)
	/*    135       */    	b0-a0
	/*    136       */    	if (b<0) jmp 122
	/*    137       */    	i11 = i11 + 1
	/*    138       */    	x0 = (65535)
.label rf2401WriteReg__end
	/*    139       */    	ret
.label WLInterruptHandler
	/*    140       */    	i11 = i11 - 1
	/*    141       */    	xmem[i11] = inp(4); i11-=1
	/*    142       */    	xmem[i11] = inp(1); i11-=1
	/*    143       */    	xmem[i11] = inp(2)
	/*    144       */    	outp(1) = nm11
	/*    145       */    	outp(2) = nm11
	/*    146       */    	i11 = i11 - 3
	/*    147       */    	xmem[i11 + 0] = a3l
	/*    148       */    	xmem[i11 + 1] = a3h
	/*    149       */    	xmem[i11 + 2] = a3g
	/*    150       */    	a3 = xmem[171]
	/*    151       */    	a3+=1
	/*    152       */    	xmem[171] = a3
	/*    153       */    	a3 = xmem[i11 + 1]
	/*    154       */    	a3l = xmem[i11 + 0]
	/*    155       */    	a3g = xmem[i11 + 2]
	/*    156       */    	i11 = i11 + 3
	/*    157       */    	outp(2) = xmem[i11]; i11+=1
	/*    158       */    	outp(1) = xmem[i11]; i11+=1
	/*    159       */    	outp(4) = xmem[i11]; i11+=1
.label WLInterruptHandler__end
	/*    160       */    	retcc
.label rf2401StandbyMode
	/*    161       */    	outp(254) = nm11
	/*    162       */    	i0 = (31)
	/*    163       */    	outp(236) = i0
	/*    164       */    	i11 = i11 - 1
	/*    165       */    	outp(224) = nm11
	/*    166       */    	nop
	/*    167       */    	nop
	/*    168       */    	outp(237) = nm11
	/*    169       */    	outp(238) = nm11
	/*    170       */    	nm0 = (16)
	/*    171       */    	outp(26) = nm0
	/*    172       */    	outp(27) = nm0
	/*    173       */    	outp(31) = nm0
	/*    174       */    	x0 = (100)
	/*    175       */    	call 451
	/*    176       */    	x1 = (0)
	/*    177       */    	x2 = (94)
	/*    178       */    	call 115
	/*    179       */    	x0 = (100)
	/*    180       */    	call 451
	/*    181       */    	x1 = (0)
	/*    182       */    	call 92
	/*    183       */    	anop; a0 = x0
	/*    184       */    	b0 = (94)
	/*    185       */    	a0-b0
	/*    186       */    	if (a==0) jmp 189
	/*    187       */    	x0 = (32993)
	/*    188       */    	call 83
.label TGT_Frf2401StandbyMode_28
	/*    189       */    	xmem[171] = nm11
	/*    190       */    	x1 = (225)
	/*    191       */    	x2 = (0)
	/*    192       */    	call 115
	/*    193       */    	x1 = (1)
	/*    194       */    	x2 = (0)
	/*    195       */    	call 115
	/*    196       */    	x1 = (4)
	/*    197       */    	x2 = (0)
	/*    198       */    	call 115
	/*    199       */    	x1 = (7)
	/*    200       */    	x2 = (112)
	/*    201       */    	call 115
	/*    202       */    	x1 = (5)
	/*    203       */    	x2 = (20)
	/*    204       */    	call 115
	/*    205       */    	b0 = (0)
.label TGT_Frf2401StandbyMode_45
	/*    206       */    	anop; x2 = b0
	/*    207       */    	xmem[i11 + 0] = x2
	/*    208       */    	x1 = (160)
	/*    209       */    	call 115
	/*    210       */    	b0 = xmem[i11 + 0]
	/*    211       */    	b0+=1
	/*    212       */    	a0 = (32)
	/*    213       */    	b0-a0
	/*    214       */    	if (b<0) jmp 206
	/*    215       */    	i0 = (6)
	/*    216       */    	outp(224) = i0
	/*    217       */    	x0 = (1)
	/*    218       */    	call 451
	/*    219       */    	i0 = (2)
	/*    220       */    	outp(224) = i0
	/*    221       */    	x0 = (1)
	/*    222       */    	call 451
	/*    223       */    	x1 = (7)
	/*    224       */    	call 92
	/*    225       */    	b0 = xmem[171]
	/*    226       */    	b0&b0
	/*    227       */    	if (b!=0) jmp 230
	/*    228       */    	x0 = (32994)
	/*    229       */    	call 83
.label TGT_Frf2401StandbyMode_69
	/*    230       */    	outp(26) = nm11
	/*    231       */    	outp(27) = nm11
	/*    232       */    	outp(31) = nm11
	/*    233       */    	x1 = (0)
	/*    234       */    	x2 = (11)
	/*    235       */    	call 115
	/*    236       */    	x1 = (0)
	/*    237       */    	call 92
	/*    238       */    	anop; a0 = x0
	/*    239       */    	b0 = (11)
	/*    240       */    	a0-b0
	/*    241       */    	if (a==0) jmp 245
	/*    242       */    	i11 = i11 + 1
	/*    243       */    	x0 = (32995)
	/*    244       */    	jmp 83
.label TGT_Frf2401StandbyMode_84
	/*    245       */    	i11 = i11 + 1
.label rf2401StandbyMode__end
	/*    246       */    	ret
.label __InitCode_parseSetup1
	/*    247       */    	i11 = i11 - 2
	/*    248       */    	xmem[i11 + 0] = i0
	/*    249       */    	nm4 = (0)
	/*    250       */    	nm0 = (0)
	/*    251       */    	i0 = (143)
	/*    252       */    	nm1 = nm4
	/*    253       */    	i4 = (36)
	/*    254       */    	i1 = (325)
	/*    255       */    	anop; x0 = xmem[i0]; i0+=1
	/*    256       */    	anop; ymem[i4] = x0; i4+=1
	/*    257       */    	anop; b0 = xmem[i1]; i1+=1
	/*    258       */    	do7, 261
	/*    259       */    	anop; x0 = xmem[i0]; i0+=1; ymem[i4] = b0; i4+=1
	/*    260       */    	anop; b0 = xmem[i1]; i1+=1
.label LE_F__InitCode_parseSetup1_14
	/*    261       */    	anop; ymem[i4] = x0; i4+=1
	/*    262       */    	i1 = (333)
	/*    263       */    	anop; x0 = xmem[i0]; i0+=1; ymem[i4] = b0; i4+=1
	/*    264       */    	anop; ymem[i4] = x0; i4+=1
	/*    265       */    	anop; b0 = xmem[i1]; i1+=1
	/*    266       */    	do4, 269
	/*    267       */    	anop; x0 = xmem[i0]; i0+=1; ymem[i4] = b0; i4+=1
	/*    268       */    	anop; b0 = xmem[i1]; i1+=1
.label LE_F__InitCode_parseSetup1_22
	/*    269       */    	anop; ymem[i4] = x0; i4+=1
	/*    270       */    	anop; x2 = xmem[i0]; ymem[i4] = b0; i4+=1
	/*    271       */    	y0 = ymem[52]
	/*    272       */    	b0 = (65533)
	/*    273       */    	nm2 = xmem[i0 + 1]
	/*    274       */    	x0 = xmem[158]
	/*    275       */    	i2 = xmem[164]
	/*    276       */    	a0 = xmem[128]
	/*    277       */    	b0 += y0
	/*    278       */    	a1 = (1)
	/*    279       */    	ymem[510] = x2
	/*    280       */    	ymem[511] = nm2
	/*    281       */    	a0-a1
	/*    282       */    	ymem[35] = x0
	/*    283       */    	ymem[63] = i2
	/*    284       */    	xmem[102] = y0
	/*    285       */    	xmem[104] = b0
	/*    286       */    	xmem[i11 + 1] = y0
	/*    287       */    	if (a!=0) jmp 299
	/*    288       */    	a0 = (64516)
	/*    289       */    	a0 += x0
	/*    290       */    	a0 = a0 << 5
	/*    291       */    	anop; x2 = a0h
	/*    292       */    	x3 = (947)
	/*    293       */    	call 2174
	/*    294       */    	a0 = xmem[i11 + 1]
	/*    295       */    	a0 -= x0
	/*    296       */    	anop; a0 = a0h
	/*    297       */    	a0-=1
	/*    298       */    	xmem[104] = a0h
.label TGT_F__InitCode_parseSetup1_52
	/*    299       */    	i3 = xmem[i11 + 0]
	/*    300       */    	i2 = i3
	/*    301       */    	nm2 = xmem[137]
	/*    302       */    	xmem[i2 += 35] = nm2
	/*    303       */    	x0 = xmem[135]
	/*    304       */    	xmem[i2 += 1] = x0
	/*    305       */    	y0 = xmem[136]
	/*    306       */    	xmem[i2 += 1] = y0
	/*    307       */    	nm2 = xmem[139]
	/*    308       */    	xmem[i2 += 1] = nm2
	/*    309       */    	nm2 = (3)
	/*    310       */    	x0 = xmem[138]
	/*    311       */    	i2 = i2 + 1
	/*    312       */    	anop; xmem[i2] = x0; i2+=n
	/*    313       */    	a0 = xmem[141]
	/*    314       */    	y0 = xmem[140]
	/*    315       */    	a1 = a0 >> 8; xmem[i2] = y0; i2-=2
	/*    316       */    	nm2 = (0)
	/*    317       */    	b0 = (255)
	/*    318       */    	a0 = a0&b0; b1 = a1h
	/*    319       */    	b1= b1&b0; xmem[i2] = a0; i2+=1
	/*    320       */    	xmem[100] = b1
	/*    321       */    	if (b!=0) jmp 326
	/*    322       */    	x0 = xmem[i3 + 40]
	/*    323       */    	a0 = (10)
	/*    324       */    	a0 += x0
	/*    325       */    	xmem[100] = a0
.label TGT_F__InitCode_parseSetup1_79
	/*    326       */    	a0 = xmem[166]
	/*    327       */    	nm2 = xmem[165]
	/*    328       */    	b0 = (65520)
	/*    329       */    	b1 = (15)
	/*    330       */    	xmem[385] = nm2
	/*    331       */    	b0= b0&a0
	/*    332       */    	b1= b1&a0
	/*    333       */    	xmem[387] = b0
	/*    334       */    	xmem[168] = b1
	/*    335       */    	nm2 = (3)
	/*    336       */    	nm3 = xmem[142]
	/*    337       */    	a1 = xmem[300]
	/*    338       */    	b1 = xmem[301]
	/*    339       */    	a0 = xmem[302]
	/*    340       */    	b0 = xmem[303]
	/*    341       */    	b3 = xmem[159]
	/*    342       */    	a3 = xmem[160]
	/*    343       */    	b2 = xmem[161]
	/*    344       */    	a2 = xmem[162]
	/*    345       */    	xmem[i2] = nm3; i2+=n
	/*    346       */    	x0 = xmem[167]
	/*    347       */    	a1 = a1|b3
	/*    348       */    	b1= b1|a3
	/*    349       */    	a0 = a0|b2
	/*    350       */    	b0= b0|a2
	/*    351       */    	xmem[159] = a1
	/*    352       */    	xmem[160] = b1
	/*    353       */    	xmem[161] = a0
	/*    354       */    	xmem[162] = b0
	/*    355       */    	xmem[388] = x0
	/*    356       */    	nm2 = (0)
	/*    357       */    	nm3 = (0)
	/*    358       */    	i3 = (159)
	/*    359       */    	do4, 361
	/*    360       */    	nm6 = xmem[i3]; i3+=1
.label LE_F__InitCode_parseSetup1_114
	/*    361       */    	xmem[i2] = nm6; i2+=1
	/*    362       */    	y0 = (1)
	/*    363       */    	x2 = xmem[161]
	/*    364       */    	x0 = xmem[159]
	/*    365       */    	a1 = y0*x2; a0 = nm3
	/*    366       */    	b0 = y0*x0; x0 = nm3
	/*    367       */    	b0 = b0>>1
	/*    368       */    	a1 = a1>>1
	/*    369       */    	x2 = xmem[162]
	/*    370       */    	b1 = b0 << 16
	/*    371       */    	a2 = a1 << 16; b0 = b1h
	/*    372       */    	b2 = y0*x2; x2 = b1l
	/*    373       */    	a1 = (0)
	/*    374       */    	b2 = b2>>1; y0 = a2l
	/*    375       */    	anop; b1 = a2h
	/*    376       */    	a1l = (65535)
	/*    377       */    	a1 = a1&b2; b1l = y0
	/*    378       */    	b1 = b1+a1; b0l = x2
	/*    379       */    	a0l = xmem[160]
	/*    380       */    	b0 = b0+a0; y1 = b1l
	/*    381       */    	anop; a1 = b1h
	/*    382       */    	anop; y0 = b0l
	/*    383       */    	anop; a0 = b0h
	/*    384       */    	i3 = (121)
	/*    385       */    	i2 = (120)
	/*    386       */    	anop; a1l = y1
	/*    387       */    	anop; a0l = y0
	/*    388       */    	anop; xymem[i3] = a1
	/*    389       */    	anop; xymem[i2] = a0
	/*    390       */    	i11 = i11 + 2
.label __InitCode_parseSetup1__end
	/*    391       */    	ret
.label __InitCode_parseSetup2
	/*    392       */    	x0 = (256)
	/*    393       */    	b0 = (290)
	/*    394       */    	b0 -= x0; y0 = i0
	/*    395       */    	b0 += y0; a0 = y0
	/*    396       */    	x0 = (32768)
	/*    397       */    	b0 += x0; i1 = a0
	/*    398       */    	anop; x1 = b0l
	/*    399       */    	anop; b0 = b0h
	/*    400       */    	anop; b0l = x1
	/*    401       */    	nm2 = (0)
	/*    402       */    	i2 = (256)
	/*    403       */    	nm1 = (0)
	/*    404       */    	jmp 408
.label TGT_F__InitCode_parseSetup2_13
	/*    405       */    	nm0 = xmem[i2]; i2+=1
	/*    406       */    	xmem[i1] = nm0; i1+=1
	/*    407       */    	anop; a0 = i1
.label __ll1___InitCode_parseSetup2
	/*    408       */    	a0 += x0
	/*    409       */    	nm0 = a0l
	/*    410       */    	anop; a0 = a0h
	/*    411       */    	a0l = nm0
	/*    412       */    	a0-b0
	/*    413       */    	if (a<0) jmp 405
	/*    414       */    	a0 = xmem[258]
	/*    415       */    	b0 = (64)
	/*    416       */    	a0&b0; x0 = nm2
	/*    417       */    	if (a!=0) jmp 420
	/*    418       */    	xmem[i0 + 43] = nm11
	/*    419       */    	ret
.label TGT_F__InitCode_parseSetup2_28
	/*    420       */    	i1 = xmem[310]
	/*    421       */    	xmem[384] = i1
	/*    422       */    	nm2 = xmem[311]
	/*    423       */    	xmem[386] = nm2
	/*    424       */    	x1 = xmem[312]
	/*    425       */    	xmem[389] = x1
	/*    426       */    	y0 = xmem[313]
	/*    427       */    	xmem[390] = y0
	/*    428       */    	a0l = xmem[314]
	/*    429       */    	xmem[391] = a0l
	/*    430       */    	a0h = xmem[315]
	/*    431       */    	xmem[392] = a0h
	/*    432       */    	i1 = xmem[316]
	/*    433       */    	xmem[393] = i1
	/*    434       */    	nm2 = xmem[317]
	/*    435       */    	b0l = xmem[318]
	/*    436       */    	xmem[394] = nm2
	/*    437       */    	b0h = xmem[319]
	/*    438       */    	xmem[395] = b0l
	/*    439       */    	x1 = xmem[320]
	/*    440       */    	xmem[396] = b0h
	/*    441       */    	y0 = xmem[321]
	/*    442       */    	xmem[397] = x1
	/*    443       */    	a0l = xmem[322]
	/*    444       */    	xmem[398] = y0
	/*    445       */    	i1 = xmem[323]
	/*    446       */    	xmem[399] = a0l
	/*    447       */    	a0h = (1)
	/*    448       */    	xmem[i0 + 43] = a0h
	/*    449       */    	xmem[400] = i1
.label __InitCode_parseSetup2__end
	/*    450       */    	ret
.label delay
	/*    451       */    	i11 = i11 - 2
	/*    452       */    	anop; b0 = x0
	/*    453       */    	jmp 473
.label TGT_Fdelay_3
	/*    454       */    	a0 = xmem[112]
	/*    455       */    	a1 = a0 >> 15
	/*    456       */    	anop; b2 = a1h
	/*    457       */    	b2= b2&b1
	/*    458       */    	b1 = b2+a0
	/*    459       */    	b1 = b1 >> 3
	/*    460       */    	xmem[i11 + 1] = b1h
	/*    461       */    	xmem[i11 + 0] = b0
	/*    462       */    	jmp 468
.label TGT_Fdelay_12
	/*    463       */    	nop
	/*    464       */    	nop
	/*    465       */    	a0 = xmem[i11 + 1]
	/*    466       */    	a0-=1
	/*    467       */    	xmem[i11 + 1] = a0
.label __ll1_delay
	/*    468       */    	b0 = xmem[i11 + 1]
	/*    469       */    	b0&b0
	/*    470       */    	if (b!=0) jmp 463
	/*    471       */    	b0 = xmem[i11 + 0]
	/*    472       */    	b0-=1
.label __ll2_delay
	/*    473       */    	b0&b0
	/*    474       */    	b1 = (7)
	/*    475       */    	if (b!=0) jmp 454
	/*    476       */    	i11 = i11 + 2
.label delay__end
	/*    477       */    	ret
.label _main
	/*    478       */    	i11 = i11 - 5
	/*    479       */    	i2 = i11 + 4
	/*    480       */    	xmem[i2] = nm11
	/*    481       */    	i0 = (384)
	/*    482       */    	nm0 = (0)
	/*    483       */    	do20, 484
.label LE_F_main_6
	/*    484       */    	xmem[i0] = nm11; i0+=1
	/*    485       */    	i2 = (36864)
	/*    486       */    	xmem[252] = nm11
	/*    487       */    	anop; b2 = i2
	/*    488       */    	y2 = (61440)
	/*    489       */    	do5, 521
	/*    490       */    	x2 = (4096)
	/*    491       */    	b2 += x2; a1,b1 = xymem[i2]; i2+=n
	/*    492       */    	a1-b1; i2 = b2
	/*    493       */    	if (a==0) jmp 496
	/*    494       */    	nm2 = (1)
	/*    495       */    	xmem[252] = nm2
.label TGT_F_main_18
	/*    496       */    	b2 += y2; a1,b1 = xymem[i2]; i2+=n
	/*    497       */    	a1-b1; i0 = b2
	/*    498       */    	if (a==0) jmp 501
	/*    499       */    	nm2 = (1)
	/*    500       */    	xmem[252] = nm2
.label TGT_F_main_23
	/*    501       */    	xmem[i11 + 0] = i0
	/*    502       */    	call 71
	/*    503       */    	a1 = xmem[i11 + 0]
	/*    504       */    	x2 = (4096)
	/*    505       */    	a1 += x2
	/*    506       */    	anop; i0 = a1
	/*    507       */    	xmem[i11 + 0] = a1
	/*    508       */    	xmem[i11 + 1] = a0l
	/*    509       */    	xmem[i11 + 2] = a0h
	/*    510       */    	call 71
	/*    511       */    	b2 = xmem[i11 + 2]
	/*    512       */    	b2l = xmem[i11 + 1]
	/*    513       */    	b2-a0
	/*    514       */    	x2 = xmem[i11 + 0]
	/*    515       */    	b2 = (61448)
	/*    516       */    	if (b==0) jmp 519
	/*    517       */    	i2 = (1)
	/*    518       */    	xmem[252] = i2
.label TGT_F_main_41
	/*    519       */    	b2 += x2
	/*    520       */    	anop; i2 = b2
.label LE_F_main_43
	/*    521       */    	y2 = (61440)
	/*    522       */    	b2 = (1)
	/*    523       */    	b2l = (0)
	/*    524       */    	xmem[226] = b2h
	/*    525       */    	i2 = (16000)
	/*    526       */    	nm2 = (64)
	/*    527       */    	xmem[112] = i2
	/*    528       */    	xmem[228] = nm2
	/*    529       */    	xmem[227] = b2l
	/*    530       */    	x0 = (2)
	/*    531       */    	call 1604
	/*    532       */    	a0 = (0)
	/*    533       */    	x1 = (1)
	/*    534       */    	i0 = (247)
	/*    535       */    	a0l = (63616)
	/*    536       */    	call 1684
	/*    537       */    	b2 = xmem[247]
	/*    538       */    	a0 = (53261)
	/*    539       */    	b2-a0
	/*    540       */    	if (b==0) jmp 558
	/*    541       */    	a0 = (52428)
	/*    542       */    	b2-a0
	/*    543       */    	a0 = (52429)
	/*    544       */    	if (b==0) jmp 555
	/*    545       */    	b2-a0
	/*    546       */    	if (b==0) jmp 552
	/*    547       */    	b2&b2
	/*    548       */    	if (b==0) jmp 739
	/*    549       */    	i2 = (43981)
	/*    550       */    	outp(768) = i2
	/*    551       */    	jmp 739
.label TGT_F_main_74
	/*    552       */    	i2 = (52429)
	/*    553       */    	outp(768) = i2
	/*    554       */    	jmp 739
.label TGT_F_main_77
	/*    555       */    	i2 = (52428)
	/*    556       */    	outp(768) = i2
	/*    557       */    	jmp 739
.label TGT_F_main_80
	/*    558       */    	a0 = (0)
	/*    559       */    	xmem[247] = nm11
	/*    560       */    	x1 = (1)
	/*    561       */    	i0 = (247)
	/*    562       */    	a0l = (63616)
	/*    563       */    	call 1742
	/*    564       */    	i2 = (126)
	/*    565       */    	b0 = (0)
	/*    566       */    	anop; a0 = xymem[i2]
	/*    567       */    	a0g = (0)
	/*    568       */    	a0 = a0 >> 10
	/*    569       */    	b2 = (0)
	/*    570       */    	b0l = (2)
	/*    571       */    	b2l = (1)
	/*    572       */    	a2 =+ a0
	/*    573       */    	if (a0>b2) b0=a2
	/*    574       */    	b2 = xmem[103]
	/*    575       */    	a0 = (2)
	/*    576       */    	b2-a0
	/*    577       */    	if (b!=0) jmp 580
	/*    578       */    	i2 = (2)
	/*    579       */    	xmem[251] = i2
.label TGT_F_main_102
	/*    580       */    	b2&b2
	/*    581       */    	if (b==0) jmp 739
	/*    582       */    	outp(398) = nm11
	/*    583       */    	i2 = (1)
	/*    584       */    	xmem[103] = nm11
	/*    585       */    	outp(394) = i2
	/*    586       */    	x0 = (5)
	/*    587       */    	xmem[i11 + 0] = b0l
	/*    588       */    	xmem[i11 + 1] = b0h
	/*    589       */    	call 451
	/*    590       */    	outp(393) = nm11
	/*    591       */    	i2 = (1)
	/*    592       */    	outp(394) = i2
	/*    593       */    	x0 = (3)
	/*    594       */    	call 451
	/*    595       */    	i2 = (10)
	/*    596       */    	outp(398) = i2
	/*    597       */    	x0 = (1)
	/*    598       */    	outp(394) = x0
	/*    599       */    	call 451
	/*    600       */    	i2 = (16)
	/*    601       */    	a0 = (192)
	/*    602       */    	xmem[i11 + 4] = i2
	/*    603       */    	x1 = (1)
	/*    604       */    	i0 = i11 + 4
	/*    605       */    	a0l = (410)
	/*    606       */    	call 1685
	/*    607       */    	y2 = (32768)
	/*    608       */    	nm2 = (1)
	/*    609       */    	x0 = (0)
	/*    610       */    	x1 = (8192)
	/*    611       */    	call 76
	/*    612       */    	i2 = xmem[109]
	/*    613       */    	b2 = (50208)
	/*    614       */    	b2 += y2; a0 = xmem[i2]
	/*    615       */    	a0 += y2; b2 = b2h
	/*    616       */    	anop; a0 = a0h
	/*    617       */    	a0-b2
	/*    618       */    	i2 = (255)
	/*    619       */    	if (a>0) jmp 627
	/*    620       */    	outp(139) = i2
	/*    621       */    	outp(144) = nm2
	/*    622       */    	i2 = (4)
	/*    623       */    	outp(395) = i2
	/*    624       */    	outp(394) = nm2
	/*    625       */    	outp(81) = i2
	/*    626       */    	jmp 635
.label TGT_F_main_149
	/*    627       */    	outp(477) = i2
	/*    628       */    	outp(476) = nm2
	/*    629       */    	x2 = (32)
	/*    630       */    	outp(465) = x2
	/*    631       */    	outp(475) = nm11
	/*    632       */    	outp(394) = nm2
	/*    633       */    	i2 = (64)
	/*    634       */    	outp(81) = i2
.label TGT_F_main_157
	/*    635       */    	i2 = (2000)
	/*    636       */    	nm2 = (3)
	/*    637       */    	xmem[112] = i2
	/*    638       */    	outp(80) = nm2
	/*    639       */    	jmp 643
.label TGT_F_main_162
	/*    640       */    	halt
	/*    641       */    	nop
	/*    642       */    	nop
.label __ll2__main
	/*    643       */    	b2 = xmem[127]
	/*    644       */    	b2&b2
	/*    645       */    	if (b==0) jmp 640
	/*    646       */    	b2 = ymem[176]
	/*    647       */    	a0 = xmem[251]
	/*    648       */    	xmem[127] = nm11
	/*    649       */    	a0 = a0|b2
	/*    650       */    	outp(67) = a0
	/*    651       */    	outp(65) = nm11
	/*    652       */    	outp(66) = nm11
	/*    653       */    	a1 = inp(64)
	/*    654       */    	a1 = a1&b2
	/*    655       */    	xmem[64] = a1
	/*    656       */    	outp(67) = a0
	/*    657       */    	if (a==0) jmp 643
	/*    658       */    	a0 = (0)
	/*    659       */    	i2 = (1)
	/*    660       */    	b2 = xmem[i11 + 1]
	/*    661       */    	xmem[119] = i2
	/*    662       */    	b2l = xmem[i11 + 0]
	/*    663       */    	xmem[i11 + 2] = a0l
	/*    664       */    	xmem[i11 + 3] = a0h
.label TGT_F_main_187
	/*    665       */    	a0 = xmem[251]
	/*    666       */    	b1 = ymem[176]
	/*    667       */    	a0 = a0|b1; a1 = a0
	/*    668       */    	outp(67) = a0
	/*    669       */    	outp(65) = nm11
	/*    670       */    	outp(66) = nm11
	/*    671       */    	a3 = inp(64)
	/*    672       */    	a3&b1
	/*    673       */    	outp(67) = a0
	/*    674       */    	if (a==0) jmp 686
	/*    675       */    	a1&a1; a0 = nm11
	/*    676       */    	if (a==0) jmp 681
	/*    677       */    	a0 = inp(64)
	/*    678       */    	a0&a1; a0 = nm11
	/*    679       */    	if (a!=0) jmp 681
	/*    680       */    	a0 = (1)
.label TGT_F_main_203
	/*    681       */    	a0&a0
	/*    682       */    	if (a!=0) jmp 686
	/*    683       */    	i2 = (1)
	/*    684       */    	xmem[119] = i2
	/*    685       */    	jmp 732
.label TGT_F_main_208
	/*    686       */    	b1 = xmem[119]
	/*    687       */    	a0 = xmem[i11 + 3]
	/*    688       */    	b1&b1
	/*    689       */    	a0l = xmem[i11 + 2]
	/*    690       */    	if (b==0) jmp 694
	/*    691       */    	xmem[119] = nm11
	/*    692       */    	b2 = (0)
	/*    693       */    	jmp 726
.label TGT_F_main_216
	/*    694       */    	b1 = (0)
	/*    695       */    	a0-b2
	/*    696       */    	b1l = (17)
	/*    697       */    	if (a<=0) jmp 725
	/*    698       */    	outp(395) = nm11
	/*    699       */    	outp(398) = nm11
	/*    700       */    	i2 = (1)
	/*    701       */    	outp(394) = i2
	/*    702       */    	xmem[i11 + 2] = a0l
	/*    703       */    	xmem[i11 + 3] = a0h
	/*    704       */    	jmp 708
.label TGT_F_main_227
	/*    705       */    	halt
	/*    706       */    	nop
	/*    707       */    	nop
.label __ll5__main
	/*    708       */    	b2 = xmem[127]
	/*    709       */    	b2&b2
	/*    710       */    	if (b==0) jmp 705
	/*    711       */    	xmem[127] = nm11
	/*    712       */    	jmp 716
.label TGT_F_main_235
	/*    713       */    	halt
	/*    714       */    	nop
	/*    715       */    	nop
.label __ll6__main
	/*    716       */    	b2 = xmem[127]
	/*    717       */    	b2&b2
	/*    718       */    	if (b==0) jmp 713
	/*    719       */    	xmem[127] = nm11
	/*    720       */    	a0 = xmem[i11 + 3]
	/*    721       */    	b1 = (0)
	/*    722       */    	outp(112) = nm11
	/*    723       */    	a0l = xmem[i11 + 2]
	/*    724       */    	b1l = (17)
.label TGT_F_main_247
	/*    725       */    	b2 = b1+a0
.label TGT_F_main_248
	/*    726       */    	xmem[i11 + 2] = b2l
	/*    727       */    	xmem[i11 + 3] = b2h
	/*    728       */    	jmp 732
.label TGT_F_main_251
	/*    729       */    	halt
	/*    730       */    	nop
	/*    731       */    	nop
.label __ll7__main
	/*    732       */    	b2 = xmem[127]
	/*    733       */    	b2&b2
	/*    734       */    	if (b==0) jmp 729
	/*    735       */    	b2 = xmem[i11 + 1]
	/*    736       */    	xmem[127] = nm11
	/*    737       */    	b2l = xmem[i11 + 0]
	/*    738       */    	jmp 665
.label TGT_F_main_261
	/*    739       */    	a0 = (0)
	/*    740       */    	xmem[103] = nm11
	/*    741       */    	x1 = (2)
	/*    742       */    	i0 = (169)
	/*    743       */    	a0l = (92)
	/*    744       */    	call 1684
	/*    745       */    	a0 = (0)
	/*    746       */    	x1 = (2)
	/*    747       */    	i0 = (245)
	/*    748       */    	a0l = (112)
	/*    749       */    	call 1684
	/*    750       */    	y0 = (32768)
	/*    751       */    	x3 = xmem[169]
	/*    752       */    	x2 = (1)
	/*    753       */    	b2 = +y0; b0 = nm11
	/*    754       */    	a0 = x2*x3; y2 = b2l
	/*    755       */    	a0 = a0>>1; b2 = b2h
	/*    756       */    	a0 = a0 << 16; b2l = y2
	/*    757       */    	x3 = xmem[245]
	/*    758       */    	b3 = x2*x3; y2 = a0l
	/*    759       */    	b3 = b3>>1; a0 = a0h
	/*    760       */    	b1 =+ b0; a0l = y2
	/*    761       */    	b3 = b3 << 16
	/*    762       */    	anop; y2 = b3l
	/*    763       */    	b0l = xmem[170]
	/*    764       */    	b0= b0|a0; b3 = b3h
	/*    765       */    	anop; b3l = y2
	/*    766       */    	b1l = xmem[246]
	/*    767       */    	xmem[113] = b0h
	/*    768       */    	b3= b3|b1; b1 = nm11
	/*    769       */    	xmem[114] = b0l
	/*    770       */    	a0 = xmem[113]
	/*    771       */    	x2,y2 = sat(b0)
	/*    772       */    	xmem[117] = b3h
	/*    773       */    	anop; a0l = y2
	/*    774       */    	xmem[118] = b3l
	/*    775       */    	a3 = xmem[117]
	/*    776       */    	x2,y2 = sat(b3)
	/*    777       */    	a0 += y0; a3l = y2
	/*    778       */    	a1 = (4)
	/*    779       */    	anop; a2 = a0h
	/*    780       */    	a0 =+ a3; x3 = a0l
	/*    781       */    	a1l = (0)
	/*    782       */    	a1 += y0; a2l = x3
	/*    783       */    	a3 += y0; x0 = a1l
	/*    784       */    	a2-b2; x2 = a3l
	/*    785       */    	anop; a1 = a1h
	/*    786       */    	anop; a3 = a3h
	/*    787       */    	xmem[i11 + 1] = b1l
	/*    788       */    	xmem[i11 + 0] = b1h
	/*    789       */    	anop; a1l = x0
	/*    790       */    	anop; a3l = x2
	/*    791       */    	i0 = (247)
	/*    792       */    	if (a<=0) jmp 799
	/*    793       */    	a2-a1
	/*    794       */    	if (a>=0) jmp 799
	/*    795       */    	a3-b2
	/*    796       */    	if (a<=0) jmp 799
	/*    797       */    	a3-a1
	/*    798       */    	if (a<0) jmp 808
.label TGT_F_main_321
	/*    799       */    	nm2 = xmem[i11 + 0]
	/*    800       */    	i2 = xmem[i11 + 1]
	/*    801       */    	xmem[117] = nm2
	/*    802       */    	xmem[113] = nm2
	/*    803       */    	x2 = (52462)
	/*    804       */    	xmem[64] = x2
	/*    805       */    	xmem[118] = i2
	/*    806       */    	xmem[114] = i2
	/*    807       */    	jmp 845
.label TGT_F_main_330
	/*    808       */    	x1 = (4)
	/*    809       */    	call 1684
	/*    810       */    	a0 = xmem[248]
	/*    811       */    	b2 = (2)
	/*    812       */    	a0-b2
	/*    813       */    	if (a!=0) jmp 818
	/*    814       */    	a0 = xmem[249]
	/*    815       */    	b2 = (128)
	/*    816       */    	a0-b2
	/*    817       */    	if (a==0) jmp 824
.label TGT_F_main_340
	/*    818       */    	nm2 = xmem[i11 + 0]
	/*    819       */    	i2 = xmem[i11 + 1]
	/*    820       */    	xmem[117] = nm2
	/*    821       */    	xmem[113] = nm2
	/*    822       */    	xmem[118] = i2
	/*    823       */    	xmem[114] = i2
.label TGT_F_main_346
	/*    824       */    	a0 = xmem[113]
	/*    825       */    	a0l = xmem[114]
	/*    826       */    	x1 = (4)
	/*    827       */    	i0 = (247)
	/*    828       */    	call 1684
	/*    829       */    	a0 = xmem[248]
	/*    830       */    	b2 = (2)
	/*    831       */    	a0-b2
	/*    832       */    	if (a!=0) jmp 837
	/*    833       */    	a0 = xmem[249]
	/*    834       */    	b2 = (256)
	/*    835       */    	a0-b2
	/*    836       */    	if (a==0) jmp 843
.label TGT_F_main_359
	/*    837       */    	nm2 = xmem[i11 + 0]
	/*    838       */    	i2 = xmem[i11 + 1]
	/*    839       */    	xmem[117] = nm2
	/*    840       */    	xmem[113] = nm2
	/*    841       */    	xmem[118] = i2
	/*    842       */    	xmem[114] = i2
.label TGT_F_main_365
	/*    843       */    	i2 = (16385)
	/*    844       */    	xmem[64] = i2
.label TGT_F_main_367
	/*    845       */    	a0 = (192)
	/*    846       */    	x1 = (1)
	/*    847       */    	i0 = (253)
	/*    848       */    	a0l = (736)
	/*    849       */    	call 1684
	/*    850       */    	call 1616
	/*    851       */    	a3 = xmem[113]
	/*    852       */    	i2 = (256)
	/*    853       */    	ymem[65] = i2
	/*    854       */    	a3l = xmem[114]
	/*    855       */    	call 67
	/*    856       */    	a3 = xmem[117]
	/*    857       */    	i2 = (512)
	/*    858       */    	ymem[65] = i2
	/*    859       */    	a3l = xmem[118]
	/*    860       */    	call 67
	/*    861       */    	x0 = (2)
	/*    862       */    	call 1604
	/*    863       */    	i2 = (32767)
	/*    864       */    	outp(80) = nm11
	/*    865       */    	xmem[101] = i2
	/*    866       */    	i0 = (197)
	/*    867       */    	call 247
	/*    868       */    	i0 = (197)
	/*    869       */    	b2 = (2)
	/*    870       */    	call 392
	/*    871       */    	a0 = xmem[128]
	/*    872       */    	a0-b2
	/*    873       */    	if (a<0) jmp 889
	/*    874       */    	b2 = xmem[144]
	/*    875       */    	y2 = (32768)
	/*    876       */    	i2 = xmem[143]
	/*    877       */    	a0 = xmem[258]
	/*    878       */    	b2 += y2
	/*    879       */    	a1 = (16)
	/*    880       */    	a0&a1; x2 = b2h
	/*    881       */    	xmem[104] = i2
	/*    882       */    	if (a!=0) jmp 884
	/*    883       */    	xmem[104] = x2
.label TGT_F_main_406
	/*    884       */    	a0 = xmem[253]
	/*    885       */    	b2 = (19987)
	/*    886       */    	a0-b2
	/*    887       */    	if (a<=0) jmp 889
	/*    888       */    	xmem[104] = x2
.label TGT_F_main_411
	/*    889       */    	a0 = xmem[198]
	/*    890       */    	a0+=1
	/*    891       */    	anop; x3 = a0
	/*    892       */    	x2 = (16000)
	/*    893       */    	call 2120
	/*    894       */    	a0 = (192)
	/*    895       */    	xmem[112] = x0
	/*    896       */    	x1 = (1)
	/*    897       */    	i0 = (239)
	/*    898       */    	a0l = (410)
	/*    899       */    	call 1685
	/*    900       */    	nm2 = (1)
	/*    901       */    	b2 = xmem[240]
	/*    902       */    	outp(402) = nm2
	/*    903       */    	b2&b2
	/*    904       */    	outp(404) = nm2
	/*    905       */    	if (b!=0) jmp 908
	/*    906       */    	i2 = (5)
	/*    907       */    	outp(210) = i2
.label TGT_F_main_430
	/*    908       */    	i0 = (197)
	/*    909       */    	call 1899
	/*    910       */    	anop; b2 = x0
	/*    911       */    	b2&b2
	/*    912       */    	if (b==0) jmp 915
	/*    913       */    	x0 = (52428)
	/*    914       */    	call 83
.label TGT_F_main_437
	/*    915       */    	i0 = (197)
	/*    916       */    	call 1293
	/*    917       */    	b2 = xmem[240]
	/*    918       */    	b2&b2
	/*    919       */    	if (b==0) jmp 1089
	/*    920       */    	x0 = (1)
	/*    921       */    	i2 = xmem[109]
	/*    922       */    	outp(202) = x0
	/*    923       */    	anop; a0 = xmem[i2]
	/*    924       */    	b2 = (50208)
	/*    925       */    	a0-b2
	/*    926       */    	if (a==0) jmp 933
	/*    927       */    	anop; a0 = xmem[i2]
	/*    928       */    	b2 = (50195)
	/*    929       */    	a0-b2
	/*    930       */    	if (a==0) jmp 933
	/*    931       */    	outp(153) = x0
	/*    932       */    	jmp 939
.label TGT_F_main_455
	/*    933       */    	outp(213) = nm11
	/*    934       */    	call 451
	/*    935       */    	i2 = (5)
	/*    936       */    	outp(210) = i2
	/*    937       */    	x0 = (1)
	/*    938       */    	call 451
.label TGT_F_main_461
	/*    939       */    	b2h = (1)
	/*    940       */    	outp(475) = b2h
	/*    941       */    	outp(478) = nm11
	/*    942       */    	nm2 = (23)
	/*    943       */    	outp(477) = nm2
	/*    944       */    	outp(476) = b2h
	/*    945       */    	x2 = (32)
	/*    946       */    	outp(465) = x2
	/*    947       */    	outp(475) = nm11
	/*    948       */    	nm2 = (7)
	/*    949       */    	a0 = xmem[324]
	/*    950       */    	outp(466) = nm2
	/*    951       */    	a0+=1
	/*    952       */    	outp(464) = a0
	/*    953       */    	i2 = xmem[109]
	/*    954       */    	outp(153) = b2h
	/*    955       */    	a0 = xmem[i2]
	/*    956       */    	b2 = (50208)
	/*    957       */    	a0-b2
	/*    958       */    	nm2 = (5)
	/*    959       */    	if (a==0) jmp 964
	/*    960       */    	a0 = xmem[i2]
	/*    961       */    	b2 = (50195)
	/*    962       */    	a0-b2
	/*    963       */    	if (a!=0) jmp 965
.label TGT_F_main_486
	/*    964       */    	outp(213) = nm11
.label TGT_F_main_487
	/*    965       */    	a0 = xmem[324]
	/*    966       */    	a0 = a0<<1
	/*    967       */    	anop; a0 = a0h
	/*    968       */    	x2 = (173)
	/*    969       */    	a0 += x2
	/*    970       */    	anop; i0 = a0
	/*    971       */    	nm0 = (0)
	/*    972       */    	outp(210) = nm2
	/*    973       */    	outp(214) = xmem[i0]; i0+=1
	/*    974       */    	outp(215) = xmem[i0]
	/*    975       */    	x0 = (1)
	/*    976       */    	call 451
	/*    977       */    	b2 = xmem[324]
	/*    978       */    	a1 = (7)
	/*    979       */    	y2 = xmem[168]
	/*    980       */    	a0 = xmem[387]
	/*    981       */    	b2-a1
	/*    982       */    	b1 = (5)
	/*    983       */    	if (b==0) jmp 1018
	/*    984       */    	b2-b1; y0 = b1
	/*    985       */    	a1 = (4)
	/*    986       */    	if (b==0) jmp 1004
	/*    987       */    	b2-a1
	/*    988       */    	if (b!=0) jmp 1021
	/*    989       */    	b2 = y2*y0
	/*    990       */    	b2 = b2>>1
	/*    991       */    	anop; x2 = b2l
	/*    992       */    	a1 = (60)
	/*    993       */    	a1 += x2
	/*    994       */    	a1 = a1 >> 3
	/*    995       */    	anop; b2 = a1h
	/*    996       */    	a0 = a0|b2
	/*    997       */    	xmem[387] = a0
	/*    998       */    	xmem[168] = b2
	/*    999       */    	b2 = xmem[384]
	/*   1000       */    	a0 = (576)
	/*   1001       */    	a0 = a0|b2
	/*   1002       */    	xmem[384] = a0
	/*   1003       */    	jmp 1021
.label TGT_F_main_526
	/*   1004       */    	anop; a1 = y2
	/*   1005       */    	a1 = a1 << 10
	/*   1006       */    	anop; b2 = a1h
	/*   1007       */    	b1 = b2 >> 2
	/*   1008       */    	b2 = b2>>1; a1 = b1h
	/*   1009       */    	anop; x2 = b2h
	/*   1010       */    	a1 += x2
	/*   1011       */    	a1 = a1 >> 10
	/*   1012       */    	anop; b2 = a1h
	/*   1013       */    	b2 += y0
	/*   1014       */    	a0 = a0|b2
	/*   1015       */    	xmem[168] = b2
	/*   1016       */    	xmem[387] = a0
	/*   1017       */    	jmp 1021
.label TGT_F_main_540
	/*   1018       */    	anop; b2 = y2
	/*   1019       */    	b2= b2|a0
	/*   1020       */    	xmem[387] = b2
.label TGT_F_main_543
	/*   1021       */    	x2 = (0)
	/*   1022       */    	i2 = (2)
	/*   1023       */    	xmem[111] = i2
	/*   1024       */    	anop; a0 = x2
	/*   1025       */    	b2 = (64)
.label TGT_F_main_548
	/*   1026       */    	b1 = xmem[384]
	/*   1027       */    	b1= b1|b2
	/*   1028       */    	anop; x3 = b1
	/*   1029       */    	xmem[i11 + 0] = a0
	/*   1030       */    	x1 = (43)
	/*   1031       */    	call 1389
	/*   1032       */    	anop; a0 = x0
	/*   1033       */    	a0&a0
	/*   1034       */    	xmem[111] = x0
	/*   1035       */    	a0 = xmem[i11 + 0]
	/*   1036       */    	if (a==0) jmp 1044
	/*   1037       */    	b2 = (2)
	/*   1038       */    	a0-b2
	/*   1039       */    	if (a!=0) jmp 1044
	/*   1040       */    	xmem[i11 + 0] = a0
	/*   1041       */    	x0 = (31128)
	/*   1042       */    	call 83
	/*   1043       */    	a0 = xmem[i11 + 0]
.label TGT_F_main_566
	/*   1044       */    	b2 = xmem[111]
	/*   1045       */    	b2&b2; x2 = nm11
	/*   1046       */    	a0+=1
	/*   1047       */    	b2 = (64)
	/*   1048       */    	if (b!=0) jmp 1026
	/*   1049       */    	i2 = (1)
	/*   1050       */    	xmem[111] = i2
	/*   1051       */    	a0 = +x2; nm0 = x2
	/*   1052       */    	i0 = (384)
.label TGT_F_main_575
	/*   1053       */    	xmem[i11 + 0] = a0
	/*   1054       */    	b2 = (0)
.label TGT_F_main_577
	/*   1055       */    	anop; x3 = xmem[i0]; i0+=1; x2 = b2
	/*   1056       */    	xmem[i11 + 1] = i0
	/*   1057       */    	xmem[i11 + 2] = x2
	/*   1058       */    	x1 = (43)
	/*   1059       */    	call 1389
	/*   1060       */    	anop; a0 = x0
	/*   1061       */    	a0&a0
	/*   1062       */    	xmem[111] = x0
	/*   1063       */    	b2 = xmem[i11 + 2]
	/*   1064       */    	a0 = (20)
	/*   1065       */    	if (a==0) jmp 1075
	/*   1066       */    	a1 = xmem[i11 + 0]
	/*   1067       */    	a3 = (2)
	/*   1068       */    	a1-a3
	/*   1069       */    	if (a!=0) jmp 1075
	/*   1070       */    	xmem[i11 + 2] = b2
	/*   1071       */    	x0 = (31129)
	/*   1072       */    	call 83
	/*   1073       */    	b2 = xmem[i11 + 2]
	/*   1074       */    	a0 = (20)
.label TGT_F_main_597
	/*   1075       */    	b2+=1
	/*   1076       */    	b2-a0
	/*   1077       */    	i0 = xmem[i11 + 1]
	/*   1078       */    	nm0 = (0)
	/*   1079       */    	if (b<0) jmp 1055
	/*   1080       */    	b2 = xmem[111]
	/*   1081       */    	a0 = xmem[i11 + 0]
	/*   1082       */    	a0+=1
	/*   1083       */    	b2&b2
	/*   1084       */    	i0 = (384)
	/*   1085       */    	if (b!=0) jmp 1053
	/*   1086       */    	i2 = (4)
	/*   1087       */    	outp(395) = i2
	/*   1088       */    	jmp 1110
.label TGT_F_main_611
	/*   1089       */    	x1 = (42)
	/*   1090       */    	x2 = (4)
	/*   1091       */    	i0 = (241)
	/*   1092       */    	call 1353
	/*   1093       */    	b2 = xmem[204]
	/*   1094       */    	a0 = (2)
	/*   1095       */    	b2= b2&a0
	/*   1096       */    	b2-a0
	/*   1097       */    	xmem[111] = x0
	/*   1098       */    	a0 = (7)
	/*   1099       */    	x2 = (173)
	/*   1100       */    	if (b==0) jmp 1102
	/*   1101       */    	a0 = (5)
.label TGT_F_main_624
	/*   1102       */    	a0 = a0<<1
	/*   1103       */    	anop; a0 = a0h
	/*   1104       */    	a0 += x2
	/*   1105       */    	anop; i0 = a0
	/*   1106       */    	nm0 = (0)
	/*   1107       */    	nop
	/*   1108       */    	outp(214) = xmem[i0]; i0+=1
	/*   1109       */    	outp(215) = xmem[i0]
.label TGT_F_main_632
	/*   1110       */    	i0 = (197)
	/*   1111       */    	call 1993
	/*   1112       */    	i0 = (197)
	/*   1113       */    	call 1939
	/*   1114       */    	i0 = (197)
	/*   1115       */    	call 1998
	/*   1116       */    	anop; b2 = x0
	/*   1117       */    	b2&b2
	/*   1118       */    	if (b==0) jmp 1121
	/*   1119       */    	i2 = (16384)
	/*   1120       */    	xmem[64] = i2
.label TGT_F_main_643
	/*   1121       */    	y2 = (0)
	/*   1122       */    	a0 = xmem[291]
	/*   1123       */    	anop; a1 = y2
	/*   1124       */    	i2 = (1865)
	/*   1125       */    	b2 = (1)
	/*   1126       */    	do15, 1136
	/*   1127       */    	b1 = b2 << y2
	/*   1128       */    	anop; a3 = b1h
	/*   1129       */    	a3&a0
	/*   1130       */    	if (a!=0) jmp 1133
	/*   1131       */    	xmem[i2] = nm11
	/*   1132       */    	jmp 1134
.label TGT_F_main_655
	/*   1133       */    	xmem[i2] = b2
.label TGT_F_main_656
	/*   1134       */    	a1+=1
	/*   1135       */    	i2 = i2 + 1
.label LE_F_main_658
	/*   1136       */    	anop; y2 = a1
	/*   1137       */    	xmem[254] = nm11
	/*   1138       */    	b2 = (0)
.label TGT_F_main_661
	/*   1139       */    	i2 = xmem[254]
	/*   1140       */    	xmem[i11 + 0] = i2
	/*   1141       */    	xmem[i11 + 1] = b2
	/*   1142       */    	call 1946
	/*   1143       */    	b2 = xmem[i11 + 1]
	/*   1144       */    	a0 = xmem[i11 + 0]
	/*   1145       */    	b2+=1
	/*   1146       */    	a0 += x0
	/*   1147       */    	a1 = (10)
	/*   1148       */    	b2-a1
	/*   1149       */    	xmem[254] = a0
	/*   1150       */    	if (b<0) jmp 1139
	/*   1151       */    	x2 = xmem[288]
	/*   1152       */    	y2 = (1)
	/*   1153       */    	b2 = y2*x2
	/*   1154       */    	b2 = b2>>1
	/*   1155       */    	b1 = b2 << 16
	/*   1156       */    	x2 = xmem[289]
	/*   1157       */    	b2 = y2*x2; a0 = b1h
	/*   1158       */    	a1 = xmem[254]
	/*   1159       */    	b2 = b2>>1; y2 = b1l
	/*   1160       */    	a3 = (5)
	/*   1161       */    	i2 = xmem[290]
	/*   1162       */    	a1-a3; a0l = y2
	/*   1163       */    	if (a>0) jmp 1212
	/*   1164       */    	a1 = inp(768)
	/*   1165       */    	b1 = (65534)
	/*   1166       */    	b1= b1&a1
	/*   1167       */    	a1 = (52428)
	/*   1168       */    	b1-a1
	/*   1169       */    	if (b==0) jmp 1188
	/*   1170       */    	y2 = (1)
	/*   1171       */    	x2 = xmem[285]
	/*   1172       */    	a0 = y2*x2
	/*   1173       */    	a0 = a0>>1
	/*   1174       */    	a0 = a0 << 16
	/*   1175       */    	y0 = xmem[286]
	/*   1176       */    	b2 = y2*y0; a1 = a0h
	/*   1177       */    	b2 = b2>>1; x2 = a0l
	/*   1178       */    	anop; a1l = x2
	/*   1179       */    	a0 = a1+b2
	/*   1180       */    	anop; b2 = a0h
	/*   1181       */    	anop; x2 = a0l
	/*   1182       */    	anop; b2l = x2
	/*   1183       */    	i2 = xmem[287]
	/*   1184       */    	xmem[226] = b2h
	/*   1185       */    	xmem[228] = i2
	/*   1186       */    	xmem[227] = b2l
	/*   1187       */    	jmp 1195
.label TGT_F_main_710
	/*   1188       */    	b1 = (0)
	/*   1189       */    	b1l = (65535)
	/*   1190       */    	b1= b1&b2
	/*   1191       */    	b1= b1|a0
	/*   1192       */    	xmem[226] = b1h
	/*   1193       */    	xmem[228] = i2
	/*   1194       */    	xmem[227] = b1l
.label TGT_F_main_717
	/*   1195       */    	x1 = (0)
	/*   1196       */    	call 1966
	/*   1197       */    	i2 = xmem[237]
	/*   1198       */    	nm2 = xmem[238]
	/*   1199       */    	outp(400) = i2
	/*   1200       */    	x2 = xmem[209]
	/*   1201       */    	outp(401) = nm2
	/*   1202       */    	y2 = xmem[206]
	/*   1203       */    	outp(403) = x2
	/*   1204       */    	a0l = xmem[207]
	/*   1205       */    	outp(406) = y2
	/*   1206       */    	outp(407) = a0l
	/*   1207       */    	x0 = (1)
	/*   1208       */    	call 451
	/*   1209       */    	i2 = xmem[205]
	/*   1210       */    	outp(405) = i2
	/*   1211       */    	jmp 1221
.label TGT_F_main_734
	/*   1212       */    	b2 = b2+a0
	/*   1213       */    	anop; a0 = b2h
	/*   1214       */    	anop; x2 = b2l
	/*   1215       */    	anop; a0l = x2
	/*   1216       */    	i3 = xmem[284]
	/*   1217       */    	xmem[226] = a0h
	/*   1218       */    	xmem[228] = i2
	/*   1219       */    	ymem[34] = i3
	/*   1220       */    	xmem[227] = a0l
.label TGT_F_main_743
	/*   1221       */    	a0 = inp(768)
	/*   1222       */    	b2 = (52429)
	/*   1223       */    	a0-b2
	/*   1224       */    	x1 = (1)
	/*   1225       */    	if (a!=0) jmp 1231
	/*   1226       */    	a0 = (0)
	/*   1227       */    	xmem[247] = nm11
	/*   1228       */    	i0 = (247)
	/*   1229       */    	a0l = (63616)
	/*   1230       */    	call 1742
.label TGT_F_main_753
	/*   1231       */    	i2 = (1)
	/*   1232       */    	outp(160) = i2
	/*   1233       */    	call 1616
	/*   1234       */    	x0 = (0)
	/*   1235       */    	x1 = (1)
	/*   1236       */    	call 76
	/*   1237       */    	i2 = xmem[260]
	/*   1238       */    	a3 = xmem[226]
	/*   1239       */    	nm2 = (768)
	/*   1240       */    	x3 = xmem[228]
	/*   1241       */    	outp(254) = i2
	/*   1242       */    	a3l = xmem[227]
	/*   1243       */    	ymem[65] = nm2
	/*   1244       */    	a0h = inp(0)
	/*   1245       */    	a1 = (255)
	/*   1246       */    	a0 = a0&a1
	/*   1247       */    	outp(0) = a0h
	/*   1248       */    	jmp 32776
	/*   1249       */    	i11 = i11 + 5
.label _main__end
	/*   1250       */    	ret
.label block
	/*   1251       */    	i11 = i11 - 1
	/*   1252       */    	xmem[i11] = inp(4); i11-=1
	/*   1253       */    	xmem[i11] = inp(1); i11-=1
	/*   1254       */    	xmem[i11] = inp(2)
	/*   1255       */    	outp(1) = nm11
	/*   1256       */    	outp(2) = nm11
	/*   1257       */    	i11 = i11 - 3
	/*   1258       */    	xmem[i11 + 0] = a3l
	/*   1259       */    	xmem[i11 + 1] = a3h
	/*   1260       */    	xmem[i11 + 2] = a3g
	/*   1261       */    	a3 = xmem[127]
	/*   1262       */    	a3+=1
	/*   1263       */    	xmem[127] = a3
	/*   1264       */    	a3 = xmem[i11 + 1]
	/*   1265       */    	a3l = xmem[i11 + 0]
	/*   1266       */    	a3g = xmem[i11 + 2]
	/*   1267       */    	i11 = i11 + 3
	/*   1268       */    	outp(2) = xmem[i11]; i11+=1
	/*   1269       */    	outp(1) = xmem[i11]; i11+=1
	/*   1270       */    	outp(4) = xmem[i11]; i11+=1
.label block__end
	/*   1271       */    	retcc
.label i2cMasterInterrupt
	/*   1272       */    	i11 = i11 - 1
	/*   1273       */    	xmem[i11] = inp(4); i11-=1
	/*   1274       */    	xmem[i11] = inp(1); i11-=1
	/*   1275       */    	xmem[i11] = inp(2)
	/*   1276       */    	outp(1) = nm11
	/*   1277       */    	outp(2) = nm11
	/*   1278       */    	i11 = i11 - 3
	/*   1279       */    	xmem[i11 + 0] = a3l
	/*   1280       */    	xmem[i11 + 1] = a3h
	/*   1281       */    	xmem[i11 + 2] = a3g
	/*   1282       */    	a3 = xmem[255]
	/*   1283       */    	a3+=1
	/*   1284       */    	xmem[255] = a3h
	/*   1285       */    	a3 = xmem[i11 + 1]
	/*   1286       */    	a3l = xmem[i11 + 0]
	/*   1287       */    	a3g = xmem[i11 + 2]
	/*   1288       */    	i11 = i11 + 3
	/*   1289       */    	outp(2) = xmem[i11]; i11+=1
	/*   1290       */    	outp(1) = xmem[i11]; i11+=1
	/*   1291       */    	outp(4) = xmem[i11]; i11+=1
.label i2cMasterInterrupt__end
	/*   1292       */    	retcc
.label i2cInititialize
	/*   1293       */    	i0 = i0 + 3
	/*   1294       */    	outp(193) = xmem[i0]
	/*   1295       */    	x1 = (1)
	/*   1296       */    	outp(192) = x1
	/*   1297       */    	x0 = (96)
	/*   1298       */    	call 76
	/*   1299       */    	xmem[255] = nm11
	/*   1300       */    	xmem[292] = nm11
.label i2cInititialize__end
	/*   1301       */    	ret
.label __i2c_i2cWaitForInt
	/*   1302       */    	b0 = xmem[101]
	/*   1303       */    	x0 = (0)
	/*   1304       */    	jmp 1314
.label TGT_F__i2c_i2cWaitForInt_3
	/*   1305       */    	a0 = xmem[255]
	/*   1306       */    	b1 = xmem[292]
	/*   1307       */    	a0-b1
	/*   1308       */    	if (a==0) jmp 1312
	/*   1309       */    	i0 = xmem[255]
	/*   1310       */    	xmem[292] = i0
	/*   1311       */    	ret
.label TGT_F__i2c_i2cWaitForInt_10
	/*   1312       */    	b0-=1
	/*   1313       */    	anop; b0 = b0h
.label __ll1___i2c_i2cWaitForInt
	/*   1314       */    	b0&b0
	/*   1315       */    	if (b!=0) jmp 1305
	/*   1316       */    	x0 = (1)
.label __i2c_i2cWaitForInt__end
	/*   1317       */    	ret
.label __i2c_i2cWaitForAck
	/*   1318       */    	call 1302
	/*   1319       */    	anop; b0 = x0
	/*   1320       */    	b0&b0
	/*   1321       */    	x0 = (1)
	/*   1322       */    	if (b!=0) jmp 1331
	/*   1323       */    	anop; x1 = x0
	/*   1324       */    	x0 = inp(199)
	/*   1325       */    	b0 = +x1; a0 = x0
	/*   1326       */    	b0&a0
	/*   1327       */    	if (b==0) jmp 1330
	/*   1328       */    	x0 = (1)
	/*   1329       */    	ret
.label TGT_F__i2c_i2cWaitForAck_12
	/*   1330       */    	x0 = (0)
.label __i2c_i2cWaitForAck__end
	/*   1331       */    	ret
.label __i2c_i2cWaitForStop
	/*   1332       */    	x1 = (0)
	/*   1333       */    	anop; b0 = x1
	/*   1334       */    	a0 = (2)
	/*   1335       */    	a1 = (100)
.label TGT_F__i2c_i2cWaitForStop_4
	/*   1336       */    	b1 = xmem[101]
	/*   1337       */    	jmp 1346
.label TGT_F__i2c_i2cWaitForStop_6
	/*   1338       */    	x0 = inp(199)
	/*   1339       */    	anop; a2 = x0
	/*   1340       */    	a2&a0
	/*   1341       */    	if (a!=0) jmp 1344
	/*   1342       */    	x0 = (0)
	/*   1343       */    	ret
.label TGT_F__i2c_i2cWaitForStop_12
	/*   1344       */    	b1-=1
	/*   1345       */    	anop; b1 = b1h
.label __ll1___i2c_i2cWaitForStop
	/*   1346       */    	b1&b1
	/*   1347       */    	if (b!=0) jmp 1338
	/*   1348       */    	b0+=1
	/*   1349       */    	b0-a1
	/*   1350       */    	if (b<0) jmp 1336
	/*   1351       */    	x0 = (1)
.label __i2c_i2cWaitForStop__end
	/*   1352       */    	ret
.label i2cWriteWords
	/*   1353       */    	xmem[255] = nm11
	/*   1354       */    	xmem[292] = nm11
	/*   1355       */    	y0 = (1)
	/*   1356       */    	outp(192) = y0
	/*   1357       */    	i1 = i0
	/*   1358       */    	nm1 = (0)
	/*   1359       */    	outp(195) = x1
	/*   1360       */    	outp(197) = xmem[i1]; i1+=1
	/*   1361       */    	a1 = +x2; y1 = i1
	/*   1362       */    	a1-=1; x0 = nm11
	/*   1363       */    	b0l = (3)
	/*   1364       */    	outp(196) = b0l
	/*   1365       */    	a1 += y1
	/*   1366       */    	jmp 1372
.label TGT_Fi2cWriteWords_14
	/*   1367       */    	call 1318
	/*   1368       */    	anop; a0 = x0
	/*   1369       */    	a0&a0
	/*   1370       */    	if (a!=0) jmp 1375
	/*   1371       */    	outp(197) = xmem[i1]; i1+=1
.label __ll1_i2cWriteWords
	/*   1372       */    	anop; b0 = i1
	/*   1373       */    	b0-a1
	/*   1374       */    	if (b!=0) jmp 1367
.label __ll2_i2cWriteWords
	/*   1375       */    	anop; x2 = x0
	/*   1376       */    	call 1318
	/*   1377       */    	b0 = +x0; a3 = x2
	/*   1378       */    	a3 = a3|b0
	/*   1379       */    	outp(196) = y0
	/*   1380       */    	call 1318
	/*   1381       */    	anop; b0 = x0
	/*   1382       */    	a3 = a3|b0
	/*   1383       */    	call 1332
	/*   1384       */    	anop; b0 = x0
	/*   1385       */    	a3 = a3|b0
	/*   1386       */    	outp(192) = nm11
	/*   1387       */    	anop; x0 = a3
.label i2cWriteWords__end
	/*   1388       */    	ret
.label i2cWriteCmd
	/*   1389       */    	xmem[255] = nm11
	/*   1390       */    	xmem[292] = nm11
	/*   1391       */    	nm0 = (1)
	/*   1392       */    	outp(192) = nm0
	/*   1393       */    	outp(195) = x1
	/*   1394       */    	outp(194) = x2
	/*   1395       */    	outp(197) = x3
	/*   1396       */    	i0 = (4)
	/*   1397       */    	outp(196) = i0
	/*   1398       */    	call 1318
	/*   1399       */    	outp(196) = nm0
	/*   1400       */    	anop; x3 = x0
	/*   1401       */    	call 1318
	/*   1402       */    	a0 = +x0; b2 = x3
	/*   1403       */    	b2= b2|a0
	/*   1404       */    	call 1332
	/*   1405       */    	anop; a0 = x0
	/*   1406       */    	b2= b2|a0
	/*   1407       */    	outp(192) = nm11
	/*   1408       */    	anop; x0 = b2
.label i2cWriteCmd__end
	/*   1409       */    	ret
.label isFlashBusy
	/*   1410       */    	i11 = i11 - 1
	/*   1411       */    	a0 = (192)
	/*   1412       */    	x1 = (1)
	/*   1413       */    	i0 = i11 + 0
	/*   1414       */    	a0l = (104)
	/*   1415       */    	call 1620
	/*   1416       */    	anop; a0 = x0
	/*   1417       */    	a0&a0
	/*   1418       */    	if (a!=0) jmp 1424
	/*   1419       */    	a0 = (1)
	/*   1420       */    	b0 = xmem[i11 + 0]
	/*   1421       */    	b0-a0; x0 = a0
	/*   1422       */    	if (b!=0) jmp 1424
	/*   1423       */    	x0 = (0)
.label TGT_FisFlashBusy_14
	/*   1424       */    	i11 = i11 + 1
.label isFlashBusy__end
	/*   1425       */    	ret
.label isPageBusy
	/*   1426       */    	i11 = i11 - 1
	/*   1427       */    	a0 = (192)
	/*   1428       */    	x1 = (1)
	/*   1429       */    	i0 = i11 + 0
	/*   1430       */    	a0l = (120)
	/*   1431       */    	call 1620
	/*   1432       */    	anop; a0 = x0
	/*   1433       */    	a0&a0
	/*   1434       */    	if (a!=0) jmp 1440
	/*   1435       */    	a0 = (1)
	/*   1436       */    	b0 = xmem[i11 + 0]
	/*   1437       */    	b0-a0; x0 = a0
	/*   1438       */    	if (b!=0) jmp 1440
	/*   1439       */    	x0 = (0)
.label TGT_FisPageBusy_14
	/*   1440       */    	i11 = i11 + 1
.label isPageBusy__end
	/*   1441       */    	ret
.label flashWaitReady
	/*   1442       */    	xmem[297] = nm11
	/*   1443       */    	xmem[296] = nm11
	/*   1444       */    	i11 = i11 - 1
	/*   1445       */    	b0 = (0)
.label TGT_FflashWaitReady_4
	/*   1446       */    	b0&b0
	/*   1447       */    	if (b!=0) jmp 1458
	/*   1448       */    	xmem[i11 + 0] = b0
	/*   1449       */    	call 1426
	/*   1450       */    	anop; b0 = x0
	/*   1451       */    	b0&b0
	/*   1452       */    	b0 = (1)
	/*   1453       */    	if (b==0) jmp 1472
	/*   1454       */    	x0 = (1)
	/*   1455       */    	call 451
	/*   1456       */    	b0 = xmem[i11 + 0]
	/*   1457       */    	jmp 1472
.label TGT_FflashWaitReady_16
	/*   1458       */    	xmem[i11 + 0] = b0
	/*   1459       */    	call 1410
	/*   1460       */    	anop; b0 = x0
	/*   1461       */    	b0&b0
	/*   1462       */    	if (b!=0) jmp 1466
	/*   1463       */    	i11 = i11 + 1
	/*   1464       */    	x0 = (0)
	/*   1465       */    	ret
.label TGT_FflashWaitReady_24
	/*   1466       */    	x0 = (1)
	/*   1467       */    	call 451
	/*   1468       */    	a0 = xmem[297]
	/*   1469       */    	a0+=1
	/*   1470       */    	xmem[297] = a0
	/*   1471       */    	b0 = xmem[i11 + 0]
.label TGT_FflashWaitReady_30
	/*   1472       */    	a0 = xmem[296]
	/*   1473       */    	a0+=1
	/*   1474       */    	a1 = (32767)
	/*   1475       */    	xmem[296] = a0
	/*   1476       */    	a0-a1
	/*   1477       */    	if (a<0) jmp 1446
	/*   1478       */    	i11 = i11 + 1
	/*   1479       */    	x0 = (1)
.label flashWaitReady__end
	/*   1480       */    	ret
.label flashNopCmd
	/*   1481       */    	i11 = i11 - 1
	/*   1482       */    	i0 = i11 + 0
	/*   1483       */    	a0 = (192)
	/*   1484       */    	xmem[i0] = nm11
	/*   1485       */    	x1 = (1)
	/*   1486       */    	a0l = (102)
	/*   1487       */    	call 1685
	/*   1488       */    	call 1442
	/*   1489       */    	i11 = i11 + 1
.label flashNopCmd__end
	/*   1490       */    	ret
.label __FlashPrimitives_setAddress
	/*   1491       */    	i11 = i11 - 1
	/*   1492       */    	i0 = i11 + 0
	/*   1493       */    	anop; xmem[i0] = x1
	/*   1494       */    	a0 = (192)
	/*   1495       */    	x1 = (1)
	/*   1496       */    	a0l = (96)
	/*   1497       */    	call 1685
	/*   1498       */    	call 1442
	/*   1499       */    	i11 = i11 + 1
.label __FlashPrimitives_setAddress__end
	/*   1500       */    	ret
.label __FlashPrimitives_loadPage
	/*   1501       */    	anop; a0 = x1
	/*   1502       */    	i11 = i11 - 1
	/*   1503       */    	i0 = i11 + 0
	/*   1504       */    	y0 = (1)
	/*   1505       */    	a0 = a0 << 9; xmem[i0] = y0
	/*   1506       */    	anop; x1 = a0h
	/*   1507       */    	call 1491
	/*   1508       */    	call 1481
	/*   1509       */    	a0 = (192)
	/*   1510       */    	x1 = (1)
	/*   1511       */    	i0 = i11 + 0
	/*   1512       */    	a0l = (124)
	/*   1513       */    	call 1685
	/*   1514       */    	call 1442
	/*   1515       */    	call 1481
	/*   1516       */    	i11 = i11 + 1
.label __FlashPrimitives_loadPage__end
	/*   1517       */    	ret
.label __FlashPrimitives_commitPage
	/*   1518       */    	i11 = i11 - 1
	/*   1519       */    	i0 = i11 + 0
	/*   1520       */    	nm0 = (2)
	/*   1521       */    	a0 = (192)
	/*   1522       */    	xmem[i0] = nm0
	/*   1523       */    	x1 = (1)
	/*   1524       */    	a0l = (124)
	/*   1525       */    	call 1685
	/*   1526       */    	x0 = (20)
	/*   1527       */    	call 451
	/*   1528       */    	call 1442
	/*   1529       */    	call 1481
	/*   1530       */    	i11 = i11 + 1
.label __FlashPrimitives_commitPage__end
	/*   1531       */    	ret
.label __FlashPrimitives_sectorErase
	/*   1532       */    	i11 = i11 - 1
	/*   1533       */    	i0 = i11 + 0
	/*   1534       */    	nm0 = (5)
	/*   1535       */    	a0 = (192)
	/*   1536       */    	xmem[i0] = nm0
	/*   1537       */    	x1 = (1)
	/*   1538       */    	a0l = (102)
	/*   1539       */    	call 1685
	/*   1540       */    	call 1442
	/*   1541       */    	i11 = i11 + 1
.label __FlashPrimitives_sectorErase__end
	/*   1542       */    	ret
.label unlock
	/*   1543       */    	i11 = i11 - 1
	/*   1544       */    	a0 = (192)
	/*   1545       */    	i0 = i11 + 0
	/*   1546       */    	x1 = (1)
	/*   1547       */    	a0l = (106)
	/*   1548       */    	call 1620
	/*   1549       */    	b0 = xmem[i11 + 0]
	/*   1550       */    	a1 =~ b0
	/*   1551       */    	a0 = (192)
	/*   1552       */    	xmem[i11 + 0] = a1h
	/*   1553       */    	x1 = (1)
	/*   1554       */    	i0 = i11 + 0
	/*   1555       */    	a0l = (106)
	/*   1556       */    	call 1685
	/*   1557       */    	i11 = i11 + 1
	/*   1558       */    	x0 = (0)
.label unlock__end
	/*   1559       */    	ret
.label __FlashPrimitives_spiSendCommand
	/*   1560       */    	a0 = (32766)
	/*   1561       */    	y0 = (32768)
	/*   1562       */    	i11 = i11 - 3
	/*   1563       */    	a0 += y0; y0 = nm11
	/*   1564       */    	xmem[i11 + 0] = a0h
	/*   1565       */    	xmem[i11 + 1] = x1
.label TGT_F__FlashPrimitives_spiSendCommand_6
	/*   1566       */    	xmem[i11 + 2] = y0
	/*   1567       */    	x0 = inp(272)
	/*   1568       */    	anop; b0 = x0
	/*   1569       */    	b0&b0
	/*   1570       */    	a0 = xmem[i11 + 2]
	/*   1571       */    	if (b==0) jmp 1593
	/*   1572       */    	i0 = xmem[i11 + 1]
	/*   1573       */    	outp(258) = i0
	/*   1574       */    	y0 = (0)
.label TGT_F__FlashPrimitives_spiSendCommand_15
	/*   1575       */    	xmem[i11 + 2] = y0
	/*   1576       */    	x0 = inp(272)
	/*   1577       */    	anop; b0 = x0
	/*   1578       */    	b0&b0
	/*   1579       */    	a0 = xmem[i11 + 2]
	/*   1580       */    	if (b==0) jmp 1584
	/*   1581       */    	i11 = i11 + 3
	/*   1582       */    	x0 = (0)
	/*   1583       */    	ret
.label TGT_F__FlashPrimitives_spiSendCommand_24
	/*   1584       */    	a0+=1
	/*   1585       */    	anop; y0 = a0h
	/*   1586       */    	b0 = (32768)
	/*   1587       */    	b0 += y0
	/*   1588       */    	anop; b0 = b0h
	/*   1589       */    	a0 = xmem[i11 + 0]
	/*   1590       */    	b0-a0
	/*   1591       */    	if (b<0) jmp 1575
	/*   1592       */    	anop; a0 = y0
.label TGT_F__FlashPrimitives_spiSendCommand_33
	/*   1593       */    	a0+=1
	/*   1594       */    	anop; y0 = a0h
	/*   1595       */    	b0 = (32768)
	/*   1596       */    	b0 += y0
	/*   1597       */    	anop; b0 = b0h
	/*   1598       */    	a0 = xmem[i11 + 0]
	/*   1599       */    	b0-a0
	/*   1600       */    	if (b<0) jmp 1566
	/*   1601       */    	i11 = i11 + 3
	/*   1602       */    	x0 = (1)
.label __FlashPrimitives_spiSendCommand__end
	/*   1603       */    	ret
.label initFlashInterface
	/*   1604       */    	i0 = (1)
	/*   1605       */    	outp(324) = i0
	/*   1606       */    	outp(323) = nm11
	/*   1607       */    	outp(327) = nm11
	/*   1608       */    	outp(326) = x0
	/*   1609       */    	x0 = inp(325)
	/*   1610       */    	nm0 = (64)
	/*   1611       */    	outp(325) = nm0
	/*   1612       */    	xmem[295] = x0
	/*   1613       */    	xmem[294] = nm0
	/*   1614       */    	outp(322) = nm0
.label initFlashInterface__end
	/*   1615       */    	ret
.label destructFlashInterface
	/*   1616       */    	nm0 = xmem[295]
	/*   1617       */    	outp(325) = nm0
	/*   1618       */    	outp(322) = nm0
.label destructFlashInterface__end
	/*   1619       */    	ret
.label npRead
	/*   1620       */    	i11 = i11 - 5
	/*   1621       */    	nm0 = (0)
	/*   1622       */    	xmem[293] = nm11
	/*   1623       */    	anop; a1 = x1
	/*   1624       */    	xmem[i11 + 1] = nm0
	/*   1625       */    	xmem[i11 + 2] = a0l
	/*   1626       */    	xmem[i11 + 3] = a0h
	/*   1627       */    	jmp 1678
.label TGT_FnpRead_8
	/*   1628       */    	b0 = xmem[293]
	/*   1629       */    	a0 = xmem[i11 + 1]
	/*   1630       */    	b0-a0
	/*   1631       */    	xmem[i11 + 4] = a1
	/*   1632       */    	if (b!=0) jmp 1670
	/*   1633       */    	a0 = xmem[294]
	/*   1634       */    	b0 = xmem[i11 + 4]
	/*   1635       */    	if (b0<a0) a0=b0
	/*   1636       */    	xmem[293] = nm11
	/*   1637       */    	outp(325) = a0
	/*   1638       */    	xmem[i11 + 1] = a0
	/*   1639       */    	nop
	/*   1640       */    	nop
	/*   1641       */    	a0 = xmem[i11 + 3]
	/*   1642       */    	a0l = xmem[i11 + 2]
	/*   1643       */    	outp(260) = a0h
	/*   1644       */    	outp(264) = a0l
	/*   1645       */    	outp(257) = nm11
	/*   1646       */    	nop
	/*   1647       */    	nop
	/*   1648       */    	b0 = xmem[i11 + 1]
	/*   1649       */    	b0 = b0<<1
	/*   1650       */    	anop; x0 = b0h
	/*   1651       */    	y0 = (1)
	/*   1652       */    	b0 = y0*x0
	/*   1653       */    	a0 = xmem[i11 + 3]
	/*   1654       */    	b0 = b0>>1
	/*   1655       */    	a0l = xmem[i11 + 2]
	/*   1656       */    	b0 = b0+a0
	/*   1657       */    	x1 = (32768)
	/*   1658       */    	xmem[i11 + 2] = b0l
	/*   1659       */    	xmem[i11 + 3] = b0h
	/*   1660       */    	call 1560
	/*   1661       */    	anop; b0 = x0
	/*   1662       */    	b0&b0
	/*   1663       */    	if (b==0) jmp 1667
	/*   1664       */    	i11 = i11 + 5
	/*   1665       */    	x0 = (1)
	/*   1666       */    	ret
.label TGT_FnpRead_47
	/*   1667       */    	outp(257) = nm11
	/*   1668       */    	nop
	/*   1669       */    	nop
.label TGT_FnpRead_50
	/*   1670       */    	x0 = inp(256)
	/*   1671       */    	i0 = xmem[i11 + 0]
	/*   1672       */    	nm0 = (0)
	/*   1673       */    	a1 = xmem[i11 + 4]
	/*   1674       */    	a1-=1; xmem[i0] = x0; i0+=1
	/*   1675       */    	b0 = xmem[293]
	/*   1676       */    	b0+=1
	/*   1677       */    	xmem[293] = b0
.label __ll1_npRead
	/*   1678       */    	a1&a1
	/*   1679       */    	xmem[i11 + 0] = i0
	/*   1680       */    	if (a!=0) jmp 1628
	/*   1681       */    	i11 = i11 + 5
	/*   1682       */    	x0 = (0)
.label npRead__end
	/*   1683       */    	ret
.label flashRead__end
.label flashRead
	/*   1684       */    	jmp 1620
.label npWrite
	/*   1685       */    	i11 = i11 - 5
	/*   1686       */    	xmem[i11 + 1] = x1
	/*   1687       */    	xmem[i11 + 2] = i0
	/*   1688       */    	xmem[i11 + 3] = a0l
	/*   1689       */    	xmem[i11 + 4] = a0h
	/*   1690       */    	jmp 1736
.label TGT_FnpWrite_6
	/*   1691       */    	a0 = xmem[294]
	/*   1692       */    	b1 = xmem[i11 + 1]
	/*   1693       */    	b0 =+ a0; a1 = b1
	/*   1694       */    	if (a0>a1) b0=b1
	/*   1695       */    	a1 = a1-b0
	/*   1696       */    	a0 = xmem[i11 + 4]
	/*   1697       */    	outp(322) = b0
	/*   1698       */    	xmem[i11 + 1] = a1
	/*   1699       */    	xmem[i11 + 0] = b0
	/*   1700       */    	a0l = xmem[i11 + 3]
	/*   1701       */    	outp(260) = a0h
	/*   1702       */    	outp(264) = a0l
	/*   1703       */    	outp(257) = nm11
	/*   1704       */    	nop
	/*   1705       */    	nop
	/*   1706       */    	a0 = xmem[i11 + 0]
	/*   1707       */    	b1 = xmem[i11 + 2]
	/*   1708       */    	a0 = a0<<1; a1 = a0
	/*   1709       */    	a0 = a1+b1; x1 = a0h
	/*   1710       */    	y0 = (1)
	/*   1711       */    	a1 = y0*x1; i0 = b1
	/*   1712       */    	b0 = xmem[i11 + 4]
	/*   1713       */    	a1 = a1>>1
	/*   1714       */    	b0l = xmem[i11 + 3]
	/*   1715       */    	b0 = b0+a1
	/*   1716       */    	nm0 = (0)
	/*   1717       */    	jmp 1720
.label TGT_FnpWrite_33
	/*   1718       */    	outp(256) = xmem[i0]; i0+=1
	/*   1719       */    	anop; b1 = i0
.label __ll1_npWrite
	/*   1720       */    	b1-a0
	/*   1721       */    	if (b!=0) jmp 1718
	/*   1722       */    	xmem[i11 + 2] = i0
	/*   1723       */    	x1 = (16384)
	/*   1724       */    	xmem[i11 + 3] = b0l
	/*   1725       */    	xmem[i11 + 4] = b0h
	/*   1726       */    	call 1560
	/*   1727       */    	anop; b0 = x0
	/*   1728       */    	b0&b0
	/*   1729       */    	if (b==0) jmp 1733
	/*   1730       */    	i11 = i11 + 5
	/*   1731       */    	x0 = (1)
	/*   1732       */    	ret
.label TGT_FnpWrite_48
	/*   1733       */    	outp(257) = nm11
	/*   1734       */    	nop
	/*   1735       */    	nop
.label __ll2_npWrite
	/*   1736       */    	b0 = xmem[i11 + 1]
	/*   1737       */    	b0&b0
	/*   1738       */    	if (b!=0) jmp 1691
	/*   1739       */    	i11 = i11 + 5
	/*   1740       */    	x0 = (0)
.label npWrite__end
	/*   1741       */    	ret
.label flashWrite
	/*   1742       */    	i11 = i11 - 8
	/*   1743       */    	a1 = a0 >> 11; b1 = x1
	/*   1744       */    	b1+=1; x0 = a1l
	/*   1745       */    	y1 = (1)
	/*   1746       */    	b0 = y1*x0; x1 = y1
	/*   1747       */    	b0 = b0>>1
	/*   1748       */    	xmem[i11 + 0] = x0
	/*   1749       */    	b0 = b0 << 11
	/*   1750       */    	b1 = b1>>1; x0 = b0l
	/*   1751       */    	anop; b0 = b0h
	/*   1752       */    	anop; b0l = x0
	/*   1753       */    	a1 = a0-b0
	/*   1754       */    	xmem[i11 + 1] = i0
	/*   1755       */    	a0 = (192)
	/*   1756       */    	i0 = i11 + 7
	/*   1757       */    	a1 = a1 >> 2; xmem[i0] = x1
	/*   1758       */    	a0l = (122)
	/*   1759       */    	xmem[i11 + 2] = a1l
	/*   1760       */    	xmem[i11 + 3] = b1h
	/*   1761       */    	call 1685
	/*   1762       */    	b0 = xmem[i11 + 0]
	/*   1763       */    	b0 = b0 << 9; a2 = nm11
	/*   1764       */    	xmem[i11 + 4] = b0h
	/*   1765       */    	y1 = xmem[i11 + 2]
	/*   1766       */    	a0 = (512)
	/*   1767       */    	jmp 1849
.label TGT_FflashWrite_26
	/*   1768       */    	a1 -= y1
	/*   1769       */    	b1 =+ a1
	/*   1770       */    	if (b0>b1) a0=a1
	/*   1771       */    	if (b0<a0) a0=b0
	/*   1772       */    	xmem[i11 + 5] = a0
	/*   1773       */    	call 1481
	/*   1774       */    	x1 = xmem[i11 + 0]
	/*   1775       */    	xmem[i11 + 6] = x0
	/*   1776       */    	call 1501
	/*   1777       */    	x1 = xmem[i11 + 4]
	/*   1778       */    	call 1491
	/*   1779       */    	b0 = xmem[i11 + 6]
	/*   1780       */    	anop; a0 = x0
	/*   1781       */    	b0= b0|a0
	/*   1782       */    	xmem[i11 + 6] = b0
	/*   1783       */    	call 1543
	/*   1784       */    	b0 = xmem[i11 + 6]
	/*   1785       */    	anop; a0 = x0
	/*   1786       */    	b0= b0|a0
	/*   1787       */    	xmem[i11 + 6] = b0
	/*   1788       */    	call 1532
	/*   1789       */    	b0 = xmem[i11 + 6]
	/*   1790       */    	anop; a0 = x0
	/*   1791       */    	b0= b0|a0
	/*   1792       */    	xmem[i11 + 6] = b0
	/*   1793       */    	call 1481
	/*   1794       */    	a0 = xmem[i11 + 2]
	/*   1795       */    	a0 = a0 << 2; b1 = x0
	/*   1796       */    	anop; x0 = a0h
	/*   1797       */    	a1 = xmem[i11 + 5]
	/*   1798       */    	y1 = (1)
	/*   1799       */    	b2 = xmem[i11 + 6]
	/*   1800       */    	a1 = a1<<1
	/*   1801       */    	b0 = y1*x0; x1 = a1h
	/*   1802       */    	a0 = (128)
	/*   1803       */    	b2= b2|b1
	/*   1804       */    	b0 = b0>>1
	/*   1805       */    	a0l = (0)
	/*   1806       */    	a0 = a0+b0
	/*   1807       */    	i0 = xmem[i11 + 1]
	/*   1808       */    	xmem[i11 + 6] = x1
	/*   1809       */    	xmem[i11 + 2] = b2
	/*   1810       */    	call 1685
	/*   1811       */    	x1 = xmem[i11 + 5]
	/*   1812       */    	b0 = xmem[i11 + 3]
	/*   1813       */    	a0 = xmem[i11 + 6]
	/*   1814       */    	y1 = xmem[i11 + 1]
	/*   1815       */    	b1 = xmem[i11 + 2]
	/*   1816       */    	b0 -= x1; a1 = x0
	/*   1817       */    	b1= b1|a1
	/*   1818       */    	a0 += y1
	/*   1819       */    	x1 = xmem[i11 + 4]
	/*   1820       */    	xmem[i11 + 1] = a0
	/*   1821       */    	xmem[i11 + 3] = b0
	/*   1822       */    	xmem[i11 + 2] = b1
	/*   1823       */    	call 1491
	/*   1824       */    	b0 = xmem[i11 + 2]
	/*   1825       */    	anop; a0 = x0
	/*   1826       */    	b0= b0|a0
	/*   1827       */    	xmem[i11 + 2] = b0
	/*   1828       */    	call 1543
	/*   1829       */    	b0 = xmem[i11 + 2]
	/*   1830       */    	anop; a0 = x0
	/*   1831       */    	b0= b0|a0
	/*   1832       */    	xmem[i11 + 2] = b0
	/*   1833       */    	call 1518
	/*   1834       */    	b0 = xmem[i11 + 2]
	/*   1835       */    	anop; a0 = x0
	/*   1836       */    	b0= b0|a0
	/*   1837       */    	xmem[i11 + 2] = b0
	/*   1838       */    	call 1481
	/*   1839       */    	b0 = xmem[i11 + 4]
	/*   1840       */    	a1 = xmem[i11 + 0]
	/*   1841       */    	a0 = (512)
	/*   1842       */    	a2 = xmem[i11 + 2]
	/*   1843       */    	a1+=1; b1 = x0
	/*   1844       */    	b0 = b0+a0; y1 = nm11
	/*   1845       */    	a2 = a2|b1
	/*   1846       */    	xmem[i11 + 2] = y1
	/*   1847       */    	xmem[i11 + 0] = a1
	/*   1848       */    	xmem[i11 + 4] = b0
.label __ll1_flashWrite
	/*   1849       */    	b0 = xmem[i11 + 3]
	/*   1850       */    	b0&b0
	/*   1851       */    	a1 = (512)
	/*   1852       */    	if (b!=0) jmp 1768
	/*   1853       */    	i11 = i11 + 8
	/*   1854       */    	anop; x0 = a2
.label flashWrite__end
	/*   1855       */    	ret
.label __ClockSetup_pllInit
	/*   1856       */    	outp(395) = nm11
	/*   1857       */    	x0 = (15)
	/*   1858       */    	outp(384) = x0
	/*   1859       */    	outp(385) = nm11
	/*   1860       */    	nm0 = (0)
	/*   1861       */    	i0 = i0 + 36
	/*   1862       */    	outp(386) = nm11
	/*   1863       */    	outp(390) = xmem[i0]; i0+=1
	/*   1864       */    	nm0 = xmem[i0]; i0-=2
	/*   1865       */    	outp(391) = nm0
	/*   1866       */    	outp(387) = xmem[i0]
	/*   1867       */    	outp(393) = nm11
	/*   1868       */    	x0 = (1)
	/*   1869       */    	outp(394) = x0
	/*   1870       */    	i0 = i0 - 28
	/*   1871       */    	outp(397) = xmem[i0]
	/*   1872       */    	call 451
	/*   1873       */    	i0 = (10)
	/*   1874       */    	outp(398) = i0
	/*   1875       */    	nm0 = (1)
	/*   1876       */    	outp(394) = nm0
.label __ClockSetup_pllInit__end
	/*   1877       */    	ret
.label __ClockSetup_xtalInit
	/*   1878       */    	nm0 = (15)
	/*   1879       */    	outp(384) = nm0
	/*   1880       */    	outp(385) = nm11
	/*   1881       */    	outp(386) = nm11
	/*   1882       */    	i0 = i0 + 35
	/*   1883       */    	outp(395) = nm11
	/*   1884       */    	outp(387) = xmem[i0]
	/*   1885       */    	nm0 = (2)
	/*   1886       */    	i0 = i0 - 30
	/*   1887       */    	outp(393) = nm0
	/*   1888       */    	outp(389) = xmem[i0]
	/*   1889       */    	x0 = (1)
	/*   1890       */    	i0 = i0 + 2
	/*   1891       */    	outp(394) = x0
	/*   1892       */    	outp(397) = xmem[i0]
	/*   1893       */    	call 451
	/*   1894       */    	i0 = (5)
	/*   1895       */    	outp(398) = i0
	/*   1896       */    	nm0 = (1)
	/*   1897       */    	outp(394) = nm0
.label __ClockSetup_xtalInit__end
	/*   1898       */    	ret
.label clockSetup
	/*   1899       */    	i11 = i11 - 2
	/*   1900       */    	nm0 = (4095)
	/*   1901       */    	outp(396) = nm0
	/*   1902       */    	xmem[i11 + 0] = i0
	/*   1903       */    	x0 = (1)
	/*   1904       */    	call 451
	/*   1905       */    	i0 = xmem[i11 + 0]
	/*   1906       */    	nm0 = (0)
	/*   1907       */    	a0 = (1)
	/*   1908       */    	b0 = xmem[i0]; i0+=2
	/*   1909       */    	b0&b0
	/*   1910       */    	outp(394) = a0
	/*   1911       */    	xmem[i11 + 1] = i0
	/*   1912       */    	if (b==0) jmp 1928
	/*   1913       */    	b0-a0
	/*   1914       */    	if (b==0) jmp 1918
	/*   1915       */    	i11 = i11 + 2
	/*   1916       */    	x0 = (1)
	/*   1917       */    	ret
.label TGT_FclockSetup_19
	/*   1918       */    	a1 = inp(398)
	/*   1919       */    	b0 = (5)
	/*   1920       */    	a1-b0
	/*   1921       */    	if (a==0) jmp 1932
	/*   1922       */    	outp(398) = nm11
	/*   1923       */    	outp(394) = a0
	/*   1924       */    	call 161
	/*   1925       */    	i0 = xmem[i11 + 0]
	/*   1926       */    	call 1878
	/*   1927       */    	jmp 1932
.label TGT_FclockSetup_29
	/*   1928       */    	outp(398) = nm11
	/*   1929       */    	outp(394) = a0
	/*   1930       */    	i0 = xmem[i11 + 0]
	/*   1931       */    	call 1856
.label TGT_FclockSetup_33
	/*   1932       */    	i0 = xmem[i11 + 1]
	/*   1933       */    	nm0 = (0)
	/*   1934       */    	i11 = i11 + 2
	/*   1935       */    	outp(81) = xmem[i0]; i0-=1
	/*   1936       */    	outp(80) = xmem[i0]
	/*   1937       */    	x0 = (0)
.label clockSetup__end
	/*   1938       */    	ret
.label clockSetupNPClockAmplitude
	/*   1939       */    	i0 = i0 + 6
	/*   1940       */    	outp(396) = xmem[i0]
	/*   1941       */    	x0 = (1)
	/*   1942       */    	call 451
	/*   1943       */    	i0 = (1)
	/*   1944       */    	outp(394) = i0
.label clockSetupNPClockAmplitude__end
	/*   1945       */    	ret
.label npReadInductiveChargeStatus
	/*   1946       */    	i11 = i11 - 1
	/*   1947       */    	a0 = (192)
	/*   1948       */    	x1 = (1)
	/*   1949       */    	i0 = i11 + 0
	/*   1950       */    	a0l = (422)
	/*   1951       */    	call 1684
	/*   1952       */    	a0 = xmem[i11 + 0]
	/*   1953       */    	b0 = (2)
	/*   1954       */    	b0&a0
	/*   1955       */    	b0 = (1)
	/*   1956       */    	if (b!=0) jmp 1963
	/*   1957       */    	b0&a0; x0 = b0
	/*   1958       */    	if (b==0) jmp 1961
	/*   1959       */    	i11 = i11 + 1
	/*   1960       */    	ret
.label TGT_FnpReadInductiveChargeStatus_15
	/*   1961       */    	x0 = (0)
	/*   1962       */    	jmp 1964
.label TGT_FnpReadInductiveChargeStatus_17
	/*   1963       */    	x0 = (2)
.label TGT_FnpReadInductiveChargeStatus_18
	/*   1964       */    	i11 = i11 + 1
.label npReadInductiveChargeStatus__end
	/*   1965       */    	ret
.label npSetInductiveChargeConfig
	/*   1966       */    	anop; b0 = x1
	/*   1967       */    	a0 = xmem[298]
	/*   1968       */    	b0&b0
	/*   1969       */    	if (b!=0) jmp 1974
	/*   1970       */    	b0 = (16)
	/*   1971       */    	b0= b0|a0
	/*   1972       */    	xmem[298] = b0
	/*   1973       */    	jmp 1977
.label TGT_FnpSetInductiveChargeConfig_8
	/*   1974       */    	b0 = (65519)
	/*   1975       */    	b0= b0&a0
	/*   1976       */    	xmem[298] = b0
.label TGT_FnpSetInductiveChargeConfig_11
	/*   1977       */    	a0 = (192)
	/*   1978       */    	x1 = (1)
	/*   1979       */    	i0 = (298)
	/*   1980       */    	a0l = (424)
	/*   1981       */    	call 1685
	/*   1982       */    	x0 = xmem[298]
.label npSetInductiveChargeConfig__end
	/*   1983       */    	ret
.label __np40_NPAdjustCurrentInj
	/*   1984       */    	i11 = i11 - 1
	/*   1985       */    	i0 = i11 + 0
	/*   1986       */    	anop; xmem[i0] = x1
	/*   1987       */    	a0 = (192)
	/*   1988       */    	x1 = (1)
	/*   1989       */    	a0l = (224)
	/*   1990       */    	call 1685
	/*   1991       */    	i11 = i11 + 1
.label __np40_NPAdjustCurrentInj__end
	/*   1992       */    	ret
.label NPSetClockInput
	/*   1993       */    	a0 = (192)
	/*   1994       */    	i0 = i0 + 23
	/*   1995       */    	x1 = (1)
	/*   1996       */    	a0l = (426)
.label NPSetClockInput__end
	/*   1997       */    	jmp 1685
.label NPChipSetup
	/*   1998       */    	i0 = i0 + 22
	/*   1999       */    	i11 = i11 - 1
	/*   2000       */    	a0 = (192)
	/*   2001       */    	xmem[i11 + 0] = i0
	/*   2002       */    	x1 = (1)
	/*   2003       */    	a0l = (420)
	/*   2004       */    	call 1685
	/*   2005       */    	i0 = xmem[i11 + 0]
	/*   2006       */    	nm0 = (22)
	/*   2007       */    	a0 = (192)
	/*   2008       */    	i1 = ymem[i0]; i0-=1
	/*   2009       */    	xmem[i11 + 0] = i0
	/*   2010       */    	x1 = (1)
	/*   2011       */    	a0l = (418)
	/*   2012       */    	call 1685
	/*   2013       */    	i0 = xmem[i11 + 0]
	/*   2014       */    	nm0 = (22)
	/*   2015       */    	a0 = (192)
	/*   2016       */    	i1 = ymem[i0]; i0-=1
	/*   2017       */    	xmem[i11 + 0] = i0
	/*   2018       */    	x1 = (1)
	/*   2019       */    	a0l = (414)
	/*   2020       */    	call 1685
	/*   2021       */    	i0 = xmem[i11 + 0]
	/*   2022       */    	nm0 = (22)
	/*   2023       */    	a0 = (192)
	/*   2024       */    	i1 = ymem[i0]; i0-=1
	/*   2025       */    	xmem[i11 + 0] = i0
	/*   2026       */    	x1 = (1)
	/*   2027       */    	a0l = (408)
	/*   2028       */    	call 1685
	/*   2029       */    	i0 = xmem[i11 + 0]
	/*   2030       */    	nm0 = (22)
	/*   2031       */    	a0 = (192)
	/*   2032       */    	i1 = ymem[i0]; i0-=1
	/*   2033       */    	xmem[i11 + 0] = i0
	/*   2034       */    	x1 = (1)
	/*   2035       */    	a0l = (404)
	/*   2036       */    	call 1685
	/*   2037       */    	i0 = xmem[i11 + 0]
	/*   2038       */    	nm0 = (22)
	/*   2039       */    	a0 = (192)
	/*   2040       */    	i1 = ymem[i0]; i0-=1
	/*   2041       */    	xmem[i11 + 0] = i0
	/*   2042       */    	x1 = (1)
	/*   2043       */    	a0l = (388)
	/*   2044       */    	call 1685
	/*   2045       */    	i0 = xmem[i11 + 0]
	/*   2046       */    	nm0 = (22)
	/*   2047       */    	a0 = (192)
	/*   2048       */    	i1 = ymem[i0]; i0-=2
	/*   2049       */    	xmem[i11 + 0] = i0
	/*   2050       */    	x1 = (1)
	/*   2051       */    	a0l = (384)
	/*   2052       */    	call 1685
	/*   2053       */    	i0 = xmem[i11 + 0]
	/*   2054       */    	a0 = (192)
	/*   2055       */    	i0 = i0 + 9
	/*   2056       */    	xmem[i11 + 0] = i0
	/*   2057       */    	x1 = (1)
	/*   2058       */    	a0l = (396)
	/*   2059       */    	call 1685
	/*   2060       */    	i0 = xmem[i11 + 0]
	/*   2061       */    	a0 = (192)
	/*   2062       */    	i0 = i0 + 1
	/*   2063       */    	xmem[i11 + 0] = i0
	/*   2064       */    	x1 = (1)
	/*   2065       */    	a0l = (394)
	/*   2066       */    	call 1685
	/*   2067       */    	i0 = xmem[i11 + 0]
	/*   2068       */    	a0 = (192)
	/*   2069       */    	i0 = i0 + 1
	/*   2070       */    	xmem[i11 + 0] = i0
	/*   2071       */    	x1 = (1)
	/*   2072       */    	a0l = (392)
	/*   2073       */    	call 1685
	/*   2074       */    	i0 = xmem[i11 + 0]
	/*   2075       */    	a0 = (192)
	/*   2076       */    	i0 = i0 + 1
	/*   2077       */    	xmem[i11 + 0] = i0
	/*   2078       */    	x1 = (1)
	/*   2079       */    	a0l = (390)
	/*   2080       */    	call 1685
	/*   2081       */    	i0 = xmem[i11 + 0]
	/*   2082       */    	a0 = (192)
	/*   2083       */    	i0 = i0 + 12
	/*   2084       */    	xmem[i11 + 0] = i0
	/*   2085       */    	x1 = (1)
	/*   2086       */    	a0l = (416)
	/*   2087       */    	call 1685
	/*   2088       */    	i0 = xmem[i11 + 0]
	/*   2089       */    	a0 = (192)
	/*   2090       */    	i0 = i0 - 16
	/*   2091       */    	xmem[i11 + 0] = i0
	/*   2092       */    	x1 = (1)
	/*   2093       */    	a0l = (426)
	/*   2094       */    	call 1685
	/*   2095       */    	i0 = xmem[i11 + 0]
	/*   2096       */    	a0 = (192)
	/*   2097       */    	i0 = i0 + 15
	/*   2098       */    	xmem[i11 + 0] = i0
	/*   2099       */    	x1 = (1)
	/*   2100       */    	a0l = (406)
	/*   2101       */    	call 1685
	/*   2102       */    	i0 = xmem[i11 + 0]
	/*   2103       */    	a0 = (192)
	/*   2104       */    	i0 = i0 - 22
	/*   2105       */    	xmem[i11 + 0] = i0
	/*   2106       */    	x1 = (1)
	/*   2107       */    	a0l = (386)
	/*   2108       */    	call 1685
	/*   2109       */    	i0 = xmem[i11 + 0]
	/*   2110       */    	nm0 = (4074)
	/*   2111       */    	nop
	/*   2112       */    	i1 = ymem[i0]; i0-=2
	/*   2113       */    	x1 = xmem[i0]
	/*   2114       */    	call 1984
	/*   2115       */    	x1 = (1)
	/*   2116       */    	call 1966
	/*   2117       */    	i11 = i11 + 1
	/*   2118       */    	x0 = (0)
.label NPChipSetup__end
	/*   2119       */    	ret
.label sdiv_called
	/*   2120       */    	b0 = +x3; a0 = x2
	/*   2121       */    	a0-b0
	/*   2122       */    	if (a==0) jmp 2170
	/*   2123       */    	a2 = (32768)
	/*   2124       */    	b0-a2
	/*   2125       */    	if (b!=0) jmp 2129
	/*   2126       */    	anop; x1 = a0
	/*   2127       */    	x0 = (0)
	/*   2128       */    	ret
.label TGT_Fsdiv_called_9
	/*   2129       */    	b3 =+ b0; a3 = nm11
	/*   2130       */    	b0= b0^a0; i0 = a3
	/*   2131       */    	a0&a0; b1 = a3
	/*   2132       */    	if (a>=0) jmp 2136
	/*   2133       */    	anop; x1 = a0
	/*   2134       */    	a0 = -x1
	/*   2135       */    	i0 = (1)
.label TGT_Fsdiv_called_16
	/*   2136       */    	b3 = |b3|
	/*   2137       */    	anop; x1 = b3
	/*   2138       */    	a1 = (1)
	/*   2139       */    	do16, 2157
	/*   2140       */    	b3 = (0)
	/*   2141       */    	if (a3<b1) b3=a1
	/*   2142       */    	a3 = a3<<1
	/*   2143       */    	a0&a2; b2 = a3h
	/*   2144       */    	if (a==0) jmp 2146
	/*   2145       */    	b2= b2|a1
.label TGT_Fsdiv_called_26
	/*   2146       */    	a0 = a0<<1
	/*   2147       */    	b3&b3; a0 = a0h
	/*   2148       */    	if (b!=0) jmp 2152
	/*   2149       */    	b2 -= x1
	/*   2150       */    	anop; a3 = b2h
	/*   2151       */    	jmp 2154
.label TGT_Fsdiv_called_32
	/*   2152       */    	b2 += x1
	/*   2153       */    	anop; a3 = b2h
.label TGT_Fsdiv_called_34
	/*   2154       */    	a3&a3
	/*   2155       */    	if (a<0) jmp 2157
	/*   2156       */    	a0 = a0|a1
.label TGT_Fsdiv_called_37
	/*   2157       */    	nop
	/*   2158       */    	a3&a3
	/*   2159       */    	if (a>=0) jmp 2163
	/*   2160       */    	a3 += x1
	/*   2161       */    	anop; x1 = a3h
	/*   2162       */    	jmp 2164
.label TGT_Fsdiv_called_43
	/*   2163       */    	anop; x1 = a3
.label TGT_Fsdiv_called_44
	/*   2164       */    	if (b0>=0) b0=a0 else b0=-a0; a0 = i0
	/*   2165       */    	a0&a0
	/*   2166       */    	if (a==0) jmp 2172
	/*   2167       */    	b1 = -x1
	/*   2168       */    	anop; x1 = b1
	/*   2169       */    	jmp 2172
.label TGT_Fsdiv_called_50
	/*   2170       */    	x1 = (0)
	/*   2171       */    	b0 = (1)
.label TGT_Fsdiv_called_52
	/*   2172       */    	anop; x0 = b0
.label sdiv_called__end
	/*   2173       */    	ret
.label udiv_called
	/*   2174       */    	a0 = (32768)
	/*   2175       */    	a0 = a0+a0; b0 = a0
	/*   2176       */    	b0 += x3; b1 = b0
	/*   2177       */    	anop; b0 = b0h
	/*   2178       */    	anop; a0 = a0h
	/*   2179       */    	b0-a0
	/*   2180       */    	if (b>=0) jmp 2211
	/*   2181       */    	b3 = +x2; b2 = nm11
	/*   2182       */    	a0 = (0)
	/*   2183       */    	b0 = (1)
	/*   2184       */    	do16, 2203
	/*   2185       */    	a2 = (0)
	/*   2186       */    	if (b2<a0) a2=b0
	/*   2187       */    	b2 = b2<<1
	/*   2188       */    	b3&b1; a1 = b2h
	/*   2189       */    	if (b==0) jmp 2191
	/*   2190       */    	a1 = a1|b0
.label TGT_Fudiv_called_17
	/*   2191       */    	b3l = (0)
	/*   2192       */    	b3 = b3<<1
	/*   2193       */    	a2&a2; b3 = b3h
	/*   2194       */    	if (a!=0) jmp 2198
	/*   2195       */    	a1 -= x3
	/*   2196       */    	anop; b2 = a1h
	/*   2197       */    	jmp 2200
.label TGT_Fudiv_called_24
	/*   2198       */    	a1 += x3
	/*   2199       */    	anop; b2 = a1h
.label TGT_Fudiv_called_26
	/*   2200       */    	b2&b2
	/*   2201       */    	if (b<0) jmp 2203
	/*   2202       */    	b3= b3|b0
.label TGT_Fudiv_called_29
	/*   2203       */    	nop
	/*   2204       */    	b2&b2; x0 = b3
	/*   2205       */    	if (b>=0) jmp 2209
	/*   2206       */    	b2 += x3
	/*   2207       */    	anop; x1 = b2h
	/*   2208       */    	ret
.label TGT_Fudiv_called_35
	/*   2209       */    	anop; x1 = b2
	/*   2210       */    	ret
.label TGT_Fudiv_called_37
	/*   2211       */    	b1 += x2; a0 = x2
	/*   2212       */    	anop; a2 = b1h
	/*   2213       */    	a2-b0
	/*   2214       */    	if (a<0) jmp 2219
	/*   2215       */    	a0 -= x3
	/*   2216       */    	anop; x1 = a0h
	/*   2217       */    	x0 = (1)
	/*   2218       */    	ret
.label TGT_Fudiv_called_45
	/*   2219       */    	anop; x1 = a0
	/*   2220       */    	x0 = (0)
.label udiv_called__end
	/*   2221       */    	ret

.bss_segment XMEM     64	    1

.bss_segment XMEM    101	    1

.data_segment XMEM    109	   
.label chip_rev
	0x9ffe

.bss_segment XMEM    111	    4

.bss_segment XMEM    117	    3

.bss_segment XMEM    127	    1

.data_segment XMEM    128	   
.label HYBRID_TEST_HybridCalibrationVersionNumberVersion
	0x0
.label HYBRID_TEST_HybridPreTestNumberHigh
	0x0
.label HYBRID_TEST_HybridPreTestNumberMiddle
	0x1
.label HYBRID_TEST_HybridPreTestNumberLow
	0x0
.label HYBRID_TEST_HybridSeriesNumberHigh
	0x0
.label HYBRID_TEST_HybridSeriesNumberMiddle
	0x0
.label HYBRID_TEST_HybridSeriesNumberLow
	0x0
.label HYBRID_TEST_RcCoarse
	0x4
.label HYBRID_TEST_RcFine
	0x6
.label HYBRID_TEST_IchargePump
	0xf1
.label HYBRID_TEST_NPResetCfg1
	0x7fe1
.label HYBRID_TEST_NPVcorePsuVcoreCtrl
	0x121
.label HYBRID_TEST_NPRfPsuCfg
	0x63
.label HYBRID_TEST_HBridgeLimit
	0x1212
.label HYBRID_TEST_HBridgeRegulator
	0x2c
.label HYBRID_TEST_ADCbattable1_1
	0x0
.label HYBRID_TEST_ADCbattable1_2
	0x0
.label HYBRID_TEST_ADCbattable1_3
	0x0
.label HYBRID_TEST_ADCbattable1_4
	0x0
.label HYBRID_TEST_ADCbattable1_5
	0x0
.label HYBRID_TEST_ADCbattable1_6
	0x0
.label HYBRID_TEST_ADCbattable1_7
	0x0
.label HYBRID_TEST_ADCbattable1_8
	0x0
.label HYBRID_TEST_ADCbattable2_1
	0x0
.label HYBRID_TEST_ADCbattable2_2
	0x0
.label HYBRID_TEST_ADCbattable2_3
	0x0
.label HYBRID_TEST_ADCbattable2_4
	0x0
.label HYBRID_TEST_ADCbattable2_5
	0x0
.label HYBRID_TEST_ADC_02V
	0x14
.label HYBRID_TEST_ADC_04V
	0x15
.label HYBRID_TEST_ADCbattogglevoltage
	0x460
.label HYBRID_TEST_ACCR1
	0x103d
.label HYBRID_TEST_ACCR2
	0x4000
.label HYBRID_TEST_ACCR3
	0x9000
.label HYBRID_TEST_ACCR4
	0x40
.label HYBRID_TEST_HFOSC
	0x3f4
.label HYBRID_TEST_InductiveCalibration
	0x4
.label HYBRID_TEST_AD4ReferencesCfg
	0x1b06
.label HYBRID_TEST_AD4CommonAnaCfg1
	0x480b
.label HYBRID_TEST_AD4CommonAnaCfg2
	0x1d6
.label antiAlias
	0x8

.data_segment XMEM    171	   
.label rfInterupt
	0x0

.rodata_segment XMEM    173	   
.label __InitCode_interpolationFilterSetup
	0x0
	0x7f
	0x8
	0xff
	0x2
	0x17f
	0x9
	0x1ff
	0x4
	0x27f
	0xa
	0x2ff
	0x6
	0x37f
	0xb
	0x3ff
	0xc
	0x4ff
	0xd
	0x5ff
	0xe
	0x6ff
	0xf
	0x7ff

.bss_segment XMEM    197	    54

.data_segment XMEM    251	   
.label BtBExtPowerMask
	0x0

.data_segment XMEM    253	   
.label __InitCode_NP_Revision
	0x4e13

.data_segment XMEM    256	   
.label HWINIT_CFG_HardwareConfiguration
	0x0
.label HWINIT_CFG_ClockDivide
	0x0
.label HWINIT_CFG_ClockEnable
	0xec
.label HWINIT_CFG_IICMasterLineSpeed
	0x9f
.label HWINIT_CFG_WL_SPI_FREQ
	0x0
.label HWINIT_CFG_XtalCload
	0xd
.label HWINIT_CFG_NPOuputClkAmplitude
	0xeee
.label HWINIT_CFG_AD2ClockConfig
	0x2
.label HWINIT_CFG_LimitRegBoost
	0x1
.label HWINIT_CFG_LimitVcoreRef
	0x0
.label HWINIT_CFG_LimitSTDCELL
	0x0
.label HWINIT_CFG_HBridgeDis
	0x0
.label HWINIT_CFG_HBridgeForceClamp
	0x0
.label HWINIT_CFG_HBridgeForceMaxLimit
	0x0
.label HWINIT_CFG_NPCurinjCtrl
	0x3
.label HWINIT_CFG_NPVcorePsu1Cap
	0x0
.label HWINIT_CFG_NPVcorePsuGainMode
	0x3
.label HWINIT_CFG_NPVcorePsuTimer
	0x0
.label HWINIT_CFG_NPVcorePsuMinclk
	0x7f
.label HWINIT_CFG_NPMiscCfg
	0x0
.label HWINIT_CFG_NPIbatCfg
	0x6
.label HWINIT_CFG_NPVbatDiodeCtrl
	0x0
.label HWINIT_CFG_NPDoublerCtrl
	0x5
.label HWINIT_CFG_NPCfgSelVcore
	0xd
.label HWINIT_CFG_NPVcorePsuThres2Down
	0x10
.label HWINIT_CFG_NPVcorePsuThres2Up
	0xe
.label HWINIT_CFG_NPVcorePsuThres1Down
	0xc
.label HWINIT_CFG_NPVcorePsuThres1Up
	0xb
.label HWINIT_CFG_BatteryFormFactor
	0x1
.label HWINIT_CFG_OsFlashLocationHigh
	0x1
.label HWINIT_CFG_OsFlashLocationLow
	0x0
.label HWINIT_CFG_OsEntryPoint
	0x40
.label HWINIT_CFG_ChargerFlashLocationHigh
	0x0
.label HWINIT_CFG_ChargerFlashLocationLow
	0xb000
.label HWINIT_CFG_ChargerEntryPoint
	0x40
.label HWINIT_CFG_InputModeDisablingRadio
	0x0

.data_segment XMEM    298	   
.label inductiveChargeConf
	0x1

.data_segment XMEM    300	   
.label HWINIT_CFG_ACCR1
	0x0
.label HWINIT_CFG_ACCR2
	0x0
.label HWINIT_CFG_ACCR3
	0x0
.label HWINIT_CFG_ACCR4
	0x0

.data_segment XMEM    310	   
.label HWINIT_CFG_AD4ChannelConfig
	0x0
.label HWINIT_CFG_AD4InputsCfg
	0x7492
.label HWINIT_CFG_AD4Ch1AnaCfg
	0x8056
.label HWINIT_CFG_AD4Ch2AnaCfg
	0x8056
.label HWINIT_CFG_AD4Ch3AnaCfg
	0x8056
.label HWINIT_CFG_AD4Ch1DigCfg1
	0x8303
.label HWINIT_CFG_AD4Ch2DigCfg1
	0x8303
.label HWINIT_CFG_AD4Ch3DigCfg1
	0x8303
.label HWINIT_CFG_AD4Ch1DigCfg2
	0x44
.label HWINIT_CFG_AD4Ch2DigCfg2
	0x44
.label HWINIT_CFG_AD4Ch3DigCfg2
	0x44
.label HWINIT_CFG_AD4Ch1DigCfg3
	0x410
.label HWINIT_CFG_AD4Ch2DigCfg3
	0x410
.label HWINIT_CFG_AD4Ch3DigCfg4
	0x410
.label HWINIT_CFG_AD4SamplerateIndex
	0x5
.label __InitCode___InitCode_parseSetup1_CalibratedVotages
	0x3f2
	0x3fc
	0x410
	0x438
	0x44c
	0x456
	0x460
	0x46a
	0x474
	0x488
	0x49c
	0x4b0
	0x4c9

.data_segment XMEM    512	   
.label X_VX_VERSION_NO
	0x3
.label X_VX_BUILD_NO
	0x6

.stack XMEM 65 65

.stack XMEM 65 65
