///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace FeatureFlag_Validation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the FeatureFlag_ValidationRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("2ab762c2-c57d-4596-8bc4-8daab666d5d7")]
    public partial class FeatureFlag_ValidationRepository : RepoGenBaseFolder
    {
        static FeatureFlag_ValidationRepository instance = new FeatureFlag_ValidationRepository();
        FeatureFlag_ValidationRepositoryFolders.SmartFit15InstallShieldWizardAppFolder _smartfit15installshieldwizard;
        FeatureFlag_ValidationRepositoryFolders.ReSoundSmartFit15InstallShieldWiAppFolder _resoundsmartfit15installshieldwi;
        FeatureFlag_ValidationRepositoryFolders.ResoundSmartFitProgramsAndFeatureAppFolder _resoundsmartfitprogramsandfeature;
        FeatureFlag_ValidationRepositoryFolders.List1000AppFolder _list1000;

        /// <summary>
        /// Gets the singleton class instance representing the FeatureFlag_ValidationRepository element repository.
        /// </summary>
        [RepositoryFolder("2ab762c2-c57d-4596-8bc4-8daab666d5d7")]
        public static FeatureFlag_ValidationRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public FeatureFlag_ValidationRepository() 
            : base("FeatureFlag_ValidationRepository", "/", null, 0, false, "2ab762c2-c57d-4596-8bc4-8daab666d5d7", ".\\RepositoryImages\\FeatureFlag_ValidationRepository2ab762c2.rximgres")
        {
            _smartfit15installshieldwizard = new FeatureFlag_ValidationRepositoryFolders.SmartFit15InstallShieldWizardAppFolder(this);
            _resoundsmartfit15installshieldwi = new FeatureFlag_ValidationRepositoryFolders.ReSoundSmartFit15InstallShieldWiAppFolder(this);
            _resoundsmartfitprogramsandfeature = new FeatureFlag_ValidationRepositoryFolders.ResoundSmartFitProgramsAndFeatureAppFolder(this);
            _list1000 = new FeatureFlag_ValidationRepositoryFolders.List1000AppFolder(this);
        }

#region Variables

        string _TxtMkt = "";

        /// <summary>
        /// Gets or sets the value of variable TxtMkt.
        /// </summary>
        [TestVariable("c2633c9b-748d-475a-84ec-2287c97232cb")]
        public string TxtMkt
        {
            get { return _TxtMkt; }
            set { _TxtMkt = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("2ab762c2-c57d-4596-8bc4-8daab666d5d7")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The SmartFit15InstallShieldWizard folder.
        /// </summary>
        [RepositoryFolder("a01d5dbf-41b2-4b48-b3c6-dab5785d6580")]
        public virtual FeatureFlag_ValidationRepositoryFolders.SmartFit15InstallShieldWizardAppFolder SmartFit15InstallShieldWizard
        {
            get { return _smartfit15installshieldwizard; }
        }

        /// <summary>
        /// The ReSoundSmartFit15InstallShieldWi folder.
        /// </summary>
        [RepositoryFolder("cd7d276d-8cd0-41c2-b3df-41633066b49f")]
        public virtual FeatureFlag_ValidationRepositoryFolders.ReSoundSmartFit15InstallShieldWiAppFolder ReSoundSmartFit15InstallShieldWi
        {
            get { return _resoundsmartfit15installshieldwi; }
        }

        /// <summary>
        /// The ResoundSmartFitProgramsAndFeature folder.
        /// </summary>
        [RepositoryFolder("0f5323be-9855-4c2e-acca-0d738899cee7")]
        public virtual FeatureFlag_ValidationRepositoryFolders.ResoundSmartFitProgramsAndFeatureAppFolder ResoundSmartFitProgramsAndFeature
        {
            get { return _resoundsmartfitprogramsandfeature; }
        }

        /// <summary>
        /// The List1000 folder.
        /// </summary>
        [RepositoryFolder("1418b82b-c150-4442-86fd-aa239dc5b3d6")]
        public virtual FeatureFlag_ValidationRepositoryFolders.List1000AppFolder List1000
        {
            get { return _list1000; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class FeatureFlag_ValidationRepositoryFolders
    {
        /// <summary>
        /// The SmartFit15InstallShieldWizardAppFolder folder.
        /// </summary>
        [RepositoryFolder("a01d5dbf-41b2-4b48-b3c6-dab5785d6580")]
        public partial class SmartFit15InstallShieldWizardAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonokInfo;

            /// <summary>
            /// Creates a new SmartFit15InstallShieldWizard  folder.
            /// </summary>
            public SmartFit15InstallShieldWizardAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SmartFit15InstallShieldWizard", "/form[@title~'Smart Fit' or @title~'Solus Max']", parentFolder, 30000, null, false, "a01d5dbf-41b2-4b48-b3c6-dab5785d6580", "")
            {
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "button[@text='&OK']", 30000, null, "9d3d6de6-63d4-40c0-9b34-e5b1673e457b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a01d5dbf-41b2-4b48-b3c6-dab5785d6580")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a01d5dbf-41b2-4b48-b3c6-dab5785d6580")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("9d3d6de6-63d4-40c0-9b34-e5b1673e457b")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("9d3d6de6-63d4-40c0-9b34-e5b1673e457b")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }
        }

        /// <summary>
        /// The ReSoundSmartFit15InstallShieldWiAppFolder folder.
        /// </summary>
        [RepositoryFolder("cd7d276d-8cd0-41c2-b3df-41633066b49f")]
        public partial class ReSoundSmartFit15InstallShieldWiAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonnextInfo;
            RepoItemInfo _iacceptthetermsinthelicenseagreemInfo;
            RepoItemInfo _checkboxstandaloneInfo;
            RepoItemInfo _somebuttonInfo;
            RepoItemInfo _combobox17344Info;
            RepoItemInfo _buttoninstallInfo;
            RepoItemInfo _buttonfinishInfo;

            /// <summary>
            /// Creates a new ReSoundSmartFit15InstallShieldWi  folder.
            /// </summary>
            public ReSoundSmartFit15InstallShieldWiAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ReSoundSmartFit15InstallShieldWi", "/form[@title~'Smart Fit' or @title~'Solus Max']", parentFolder, 30000, null, false, "cd7d276d-8cd0-41c2-b3df-41633066b49f", "")
            {
                _buttonnextInfo = new RepoItemInfo(this, "ButtonNext", "button[@text='&Next >']", 30000, null, "c86c128d-6535-439c-b321-12f8a5220bc7");
                _iacceptthetermsinthelicenseagreemInfo = new RepoItemInfo(this, "IAcceptTheTermsInTheLicenseAgreem", "?/?/radiobutton[@text>'I &accept the terms in the']", 30000, null, "51a595a8-cafd-4e8e-89f6-22957b54b180");
                _checkboxstandaloneInfo = new RepoItemInfo(this, "CheckBoxStandalone", "checkbox[@text='&Standalone']", 30000, null, "3fd660df-44ed-4931-851f-37465f81e6ff");
                _somebuttonInfo = new RepoItemInfo(this, "SomeButton", "?/?/button[@text='>']", 30000, null, "56e93d18-a0d0-4646-8aff-c2216896810b");
                _combobox17344Info = new RepoItemInfo(this, "ComboBox17344", "combobox[@controlid='17344' or @controlid='17062']", 30000, null, "d26d10ee-9320-444b-9600-d666d6c228ba");
                _buttoninstallInfo = new RepoItemInfo(this, "ButtonInstall", "button[@text='&Install']", 30000, null, "0b99a7c2-3704-4587-beff-994cf8567b15");
                _buttonfinishInfo = new RepoItemInfo(this, "ButtonFinish", "button[@text='&Finish']", 600000, null, "241d1bbe-7e04-4a97-a3e7-172b75d2e453");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("cd7d276d-8cd0-41c2-b3df-41633066b49f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cd7d276d-8cd0-41c2-b3df-41633066b49f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonNext item.
            /// </summary>
            [RepositoryItem("c86c128d-6535-439c-b321-12f8a5220bc7")]
            public virtual Ranorex.Button ButtonNext
            {
                get
                {
                    return _buttonnextInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonNext item info.
            /// </summary>
            [RepositoryItemInfo("c86c128d-6535-439c-b321-12f8a5220bc7")]
            public virtual RepoItemInfo ButtonNextInfo
            {
                get
                {
                    return _buttonnextInfo;
                }
            }

            /// <summary>
            /// The IAcceptTheTermsInTheLicenseAgreem item.
            /// </summary>
            [RepositoryItem("51a595a8-cafd-4e8e-89f6-22957b54b180")]
            public virtual Ranorex.RadioButton IAcceptTheTermsInTheLicenseAgreem
            {
                get
                {
                    return _iacceptthetermsinthelicenseagreemInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The IAcceptTheTermsInTheLicenseAgreem item info.
            /// </summary>
            [RepositoryItemInfo("51a595a8-cafd-4e8e-89f6-22957b54b180")]
            public virtual RepoItemInfo IAcceptTheTermsInTheLicenseAgreemInfo
            {
                get
                {
                    return _iacceptthetermsinthelicenseagreemInfo;
                }
            }

            /// <summary>
            /// The CheckBoxStandalone item.
            /// </summary>
            [RepositoryItem("3fd660df-44ed-4931-851f-37465f81e6ff")]
            public virtual Ranorex.CheckBox CheckBoxStandalone
            {
                get
                {
                    return _checkboxstandaloneInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The CheckBoxStandalone item info.
            /// </summary>
            [RepositoryItemInfo("3fd660df-44ed-4931-851f-37465f81e6ff")]
            public virtual RepoItemInfo CheckBoxStandaloneInfo
            {
                get
                {
                    return _checkboxstandaloneInfo;
                }
            }

            /// <summary>
            /// The SomeButton item.
            /// </summary>
            [RepositoryItem("56e93d18-a0d0-4646-8aff-c2216896810b")]
            public virtual Ranorex.Button SomeButton
            {
                get
                {
                    return _somebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SomeButton item info.
            /// </summary>
            [RepositoryItemInfo("56e93d18-a0d0-4646-8aff-c2216896810b")]
            public virtual RepoItemInfo SomeButtonInfo
            {
                get
                {
                    return _somebuttonInfo;
                }
            }

            /// <summary>
            /// The ComboBox17344 item.
            /// </summary>
            [RepositoryItem("d26d10ee-9320-444b-9600-d666d6c228ba")]
            public virtual Ranorex.ComboBox ComboBox17344
            {
                get
                {
                    return _combobox17344Info.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The ComboBox17344 item info.
            /// </summary>
            [RepositoryItemInfo("d26d10ee-9320-444b-9600-d666d6c228ba")]
            public virtual RepoItemInfo ComboBox17344Info
            {
                get
                {
                    return _combobox17344Info;
                }
            }

            /// <summary>
            /// The ButtonInstall item.
            /// </summary>
            [RepositoryItem("0b99a7c2-3704-4587-beff-994cf8567b15")]
            public virtual Ranorex.Button ButtonInstall
            {
                get
                {
                    return _buttoninstallInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonInstall item info.
            /// </summary>
            [RepositoryItemInfo("0b99a7c2-3704-4587-beff-994cf8567b15")]
            public virtual RepoItemInfo ButtonInstallInfo
            {
                get
                {
                    return _buttoninstallInfo;
                }
            }

            /// <summary>
            /// The ButtonFinish item.
            /// </summary>
            [RepositoryItem("241d1bbe-7e04-4a97-a3e7-172b75d2e453")]
            public virtual Ranorex.Button ButtonFinish
            {
                get
                {
                    return _buttonfinishInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonFinish item info.
            /// </summary>
            [RepositoryItemInfo("241d1bbe-7e04-4a97-a3e7-172b75d2e453")]
            public virtual RepoItemInfo ButtonFinishInfo
            {
                get
                {
                    return _buttonfinishInfo;
                }
            }
        }

        /// <summary>
        /// The ResoundSmartFitProgramsAndFeatureAppFolder folder.
        /// </summary>
        [RepositoryFolder("0f5323be-9855-4c2e-acca-0d738899cee7")]
        public partial class ResoundSmartFitProgramsAndFeatureAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _resoundsmartfit15Info;
            RepoItemInfo _closeInfo;
            RepoItemInfo _combobox17062Info;
            RepoItemInfo _combobox17451Info;

            /// <summary>
            /// Creates a new ResoundSmartFitProgramsAndFeature  folder.
            /// </summary>
            public ResoundSmartFitProgramsAndFeatureAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ResoundSmartFitProgramsAndFeature", "/form[@title~'Smart Fit' or @title~'Solus Max']", parentFolder, 30000, null, false, "0f5323be-9855-4c2e-acca-0d738899cee7", "")
            {
                _resoundsmartfit15Info = new RepoItemInfo(this, "ReSoundSmartFit15", ".//container[@caption='ShellView']/table[@controlid='1']/row[@index='0']/cell[@text='ReSound Smart Fit 1.5']", 30000, null, "41e178d4-0d97-4be1-9e0f-2086ede18f21");
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/button[@accessiblename='Close']", 30000, null, "a0161b2a-44f1-405c-8500-979db644eb42");
                _combobox17062Info = new RepoItemInfo(this, "ComboBox17062", "combobox[@controlid='17062']", 30000, null, "e246efa5-b0be-40d5-a680-6feb31da98f4");
                _combobox17451Info = new RepoItemInfo(this, "ComboBox17451", "combobox[@class='ComboBox']", 30000, null, "5f9def0d-c894-4ef2-ab4e-982ec4725cab");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0f5323be-9855-4c2e-acca-0d738899cee7")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0f5323be-9855-4c2e-acca-0d738899cee7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ReSoundSmartFit15 item.
            /// </summary>
            [RepositoryItem("41e178d4-0d97-4be1-9e0f-2086ede18f21")]
            public virtual Ranorex.Cell ReSoundSmartFit15
            {
                get
                {
                    return _resoundsmartfit15Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ReSoundSmartFit15 item info.
            /// </summary>
            [RepositoryItemInfo("41e178d4-0d97-4be1-9e0f-2086ede18f21")]
            public virtual RepoItemInfo ReSoundSmartFit15Info
            {
                get
                {
                    return _resoundsmartfit15Info;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("a0161b2a-44f1-405c-8500-979db644eb42")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("a0161b2a-44f1-405c-8500-979db644eb42")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }

            /// <summary>
            /// The ComboBox17062 item.
            /// </summary>
            [RepositoryItem("e246efa5-b0be-40d5-a680-6feb31da98f4")]
            public virtual Ranorex.ComboBox ComboBox17062
            {
                get
                {
                    return _combobox17062Info.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The ComboBox17062 item info.
            /// </summary>
            [RepositoryItemInfo("e246efa5-b0be-40d5-a680-6feb31da98f4")]
            public virtual RepoItemInfo ComboBox17062Info
            {
                get
                {
                    return _combobox17062Info;
                }
            }

            /// <summary>
            /// The ComboBox17451 item.
            /// </summary>
            [RepositoryItem("5f9def0d-c894-4ef2-ab4e-982ec4725cab")]
            public virtual Ranorex.ComboBox ComboBox17451
            {
                get
                {
                    return _combobox17451Info.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The ComboBox17451 item info.
            /// </summary>
            [RepositoryItemInfo("5f9def0d-c894-4ef2-ab4e-982ec4725cab")]
            public virtual RepoItemInfo ComboBox17451Info
            {
                get
                {
                    return _combobox17451Info;
                }
            }
        }

        /// <summary>
        /// The List1000AppFolder folder.
        /// </summary>
        [RepositoryFolder("1418b82b-c150-4442-86fd-aa239dc5b3d6")]
        public partial class List1000AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _australiaInfo;
            RepoItemInfo _someindicatorInfo;

            /// <summary>
            /// Creates a new List1000  folder.
            /// </summary>
            public List1000AppFolder(RepoGenBaseFolder parentFolder) :
                    base("List1000", "/list[@controlid='1000']", parentFolder, 30000, null, false, "1418b82b-c150-4442-86fd-aa239dc5b3d6", "")
            {
                _australiaInfo = new RepoItemInfo(this, "Australia", "listitem[@text=$TxtMkt]", 30000, null, "c93ec61c-65fb-48cd-b5ce-f288e8f834c2");
                _someindicatorInfo = new RepoItemInfo(this, "SomeIndicator", "?/?/indicator", 30000, null, "1310a587-f011-4e61-832d-48ac8faabadd");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1418b82b-c150-4442-86fd-aa239dc5b3d6")]
            public virtual Ranorex.List Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1418b82b-c150-4442-86fd-aa239dc5b3d6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Australia item.
            /// </summary>
            [RepositoryItem("c93ec61c-65fb-48cd-b5ce-f288e8f834c2")]
            public virtual Ranorex.ListItem Australia
            {
                get
                {
                    return _australiaInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Australia item info.
            /// </summary>
            [RepositoryItemInfo("c93ec61c-65fb-48cd-b5ce-f288e8f834c2")]
            public virtual RepoItemInfo AustraliaInfo
            {
                get
                {
                    return _australiaInfo;
                }
            }

            /// <summary>
            /// The SomeIndicator item.
            /// </summary>
            [RepositoryItem("1310a587-f011-4e61-832d-48ac8faabadd")]
            public virtual Ranorex.Indicator SomeIndicator
            {
                get
                {
                    return _someindicatorInfo.CreateAdapter<Ranorex.Indicator>(true);
                }
            }

            /// <summary>
            /// The SomeIndicator item info.
            /// </summary>
            [RepositoryItemInfo("1310a587-f011-4e61-832d-48ac8faabadd")]
            public virtual RepoItemInfo SomeIndicatorInfo
            {
                get
                {
                    return _someindicatorInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
